Repository apache/iotdb, pull requests merged in 2021-04, with the labels that each got.

#2952 [ISSUE-2730] Change the upgraded TsFile names
  server/src/main/java/org/apache/iotdb/db/tools/upgrade/TsFileOnlineUpgradeTool.java
Labels: Module - Upgrade Tool

#2937 [ISSUE-2919] Fix C++ client memory leak bug
  client-cpp/src/main/Session.cpp
  client-cpp/src/main/Session.h
  example/client-cpp-example/src/SessionExample.cpp
Labels: Module - C++ client

#2953 fix stackoverflow when parse plan failed
  cross-tests/src/test/java/org/apache/iotdb/cross/tests/tools/importCsv/AbstractScript.java
  cross-tests/src/test/java/org/apache/iotdb/cross/tests/tools/importCsv/ExportCsvTestIT.java
  cross-tests/src/test/java/org/apache/iotdb/cross/tests/tools/importCsv/ImportCsvTestIT.java
  server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertMultiTabletPlan.java
  server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertRowsPlan.java
  server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertTabletPlan.java
  server/src/main/java/org/apache/iotdb/db/qp/physical/sys/CreateMultiTimeSeriesPlan.java
Labels: Module - Cluster, bug

#2848 [IOTDB-1276]Add explain sql support and remove debug_state parameter
  antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/SqlBase.g4
  cluster/src/main/java/org/apache/iotdb/cluster/query/RemoteQueryContext.java
  cluster/src/main/java/org/apache/iotdb/cluster/server/ClientServer.java
  server/file-changelists/conf-changelist.md
  server/src/assembly/resources/conf/iotdb-engine.properties
  server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
  server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
  server/src/main/java/org/apache/iotdb/db/engine/cache/ChunkCache.java
  server/src/main/java/org/apache/iotdb/db/engine/cache/TimeSeriesMetadataCache.java
  server/src/main/java/org/apache/iotdb/db/engine/modification/Deletion.java
  server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java
  server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessor.java
  server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java
  server/src/main/java/org/apache/iotdb/db/qp/logical/Operator.java
  server/src/main/java/org/apache/iotdb/db/qp/physical/PhysicalPlan.java
  server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java
  server/src/main/java/org/apache/iotdb/db/qp/strategy/PhysicalGenerator.java
  server/src/main/java/org/apache/iotdb/db/query/context/QueryContext.java
  server/src/main/java/org/apache/iotdb/db/query/executor/LastQueryExecutor.java
  server/src/main/java/org/apache/iotdb/db/query/reader/chunk/DiskChunkLoader.java
  server/src/main/java/org/apache/iotdb/db/query/reader/chunk/metadata/DiskChunkMetadataLoader.java
  server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java
  server/src/main/java/org/apache/iotdb/db/utils/FileLoaderUtils.java
  tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/ChunkMetadata.java
  tsfile/src/main/java/org/apache/iotdb/tsfile/file/metadata/TimeseriesMetadata.java
Labels: 0.12.0

#2962 Fix incompatible max_degree_of_index_node
  docs/UserGuide/Server/Config Manual.md
  docs/zh/UserGuide/Server/Config Manual.md
  server/src/test/java/org/apache/iotdb/db/integration/IoTDBCheckConfigIT.java
  tsfile/src/main/java/org/apache/iotdb/tsfile/common/conf/TSFileConfig.java
Labels: 0.12.0

#2864 [IOTDB-1230]Support cross multi time partition when loading one TsFile
  example/tsfile/src/main/java/org/apache/iotdb/tsfile/TsFileRead.java
  example/tsfile/src/main/java/org/apache/iotdb/tsfile/TsFileWriteWithTSRecord.java
  example/tsfile/src/main/java/org/apache/iotdb/tsfile/TsFileWriteWithTablet.java
  server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java
  server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileResource.java
  server/src/main/java/org/apache/iotdb/db/engine/storagegroup/timeindex/DeviceTimeIndex.java
  server/src/main/java/org/apache/iotdb/db/engine/storagegroup/timeindex/FileTimeIndex.java
  server/src/main/java/org/apache/iotdb/db/engine/storagegroup/timeindex/ITimeIndex.java
  server/src/main/java/org/apache/iotdb/db/engine/upgrade/UpgradeTask.java
  server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java
  server/src/main/java/org/apache/iotdb/db/tools/TsFileRewriteTool.java
  server/src/main/java/org/apache/iotdb/db/tools/upgrade/TsFileOnlineUpgradeTool.java
  server/src/test/java/org/apache/iotdb/db/utils/TsFileRewriteToolTest.java
Labels: 0.12.0, Module - Storage Engine

#2967 Log more memory usage information in SystemInfo
  server/src/main/java/org/apache/iotdb/db/rescon/SystemInfo.java
Labels: 0.12.0

#2776 [IOTDB-1190]Fully support HTTP URL char set in IoTDB path
  server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
Labels: 0.12.0

#2795 [IOTDB-1202] reduce the size of client library
  README.md
  README_ZH.md
  cluster/pom.xml
  cluster/src/main/java/org/apache/iotdb/cluster/RemoteTsFileResource.java
  cluster/src/main/java/org/apache/iotdb/cluster/log/HardState.java
  cluster/src/main/java/org/apache/iotdb/cluster/log/logtypes/AddNodeLog.java
  cluster/src/main/java/org/apache/iotdb/cluster/log/logtypes/RemoveNodeLog.java
  cluster/src/main/java/org/apache/iotdb/cluster/log/snapshot/PullSnapshotTaskDescriptor.java
  cluster/src/main/java/org/apache/iotdb/cluster/partition/slot/SlotManager.java
  cluster/src/main/java/org/apache/iotdb/cluster/partition/slot/SlotPartitionTable.java
  cluster/src/main/java/org/apache/iotdb/cluster/utils/NodeSerializeUtils.java
  cluster/src/test/java/org/apache/iotdb/cluster/utils/SerializeUtilTest.java
  code-coverage/pom.xml
  docs/Development/ContributeGuide.md
  grafana/pom.xml
  jdbc/pom.xml
  pom.xml
  server/pom.xml
  server/src/main/java/org/apache/iotdb/db/utils/SerializeUtils.java
  server/src/test/java/org/apache/iotdb/db/utils/SerializeUtilsTest.java
  service-rpc/pom.xml
  session/pom.xml
  thrift-cluster/README.md
  thrift-cluster/pom.xml
  thrift-cluster/rpc-changelist.md
  thrift-cluster/src/main/thrift/cluster.thrift
  thrift-sync/README.md
  thrift-sync/pom.xml
  thrift-sync/rpc-changelist.md
  thrift-sync/src/main/thrift/sync.thrift
  thrift/README.md
Labels: 0.12.0

#2964 Fix group by month bug
  cluster/src/test/java/org/apache/iotdb/cluster/query/groupby/ClusterGroupByNoVFilterDataSetTest.java
  server/src/main/java/org/apache/iotdb/db/query/dataset/groupby/GroupByWithoutValueFilterDataSet.java
  server/src/main/java/org/apache/iotdb/db/query/executor/QueryRouter.java
  server/src/test/java/org/apache/iotdb/db/integration/IOTDBGroupByIT.java
  server/src/test/java/org/apache/iotdb/db/integration/IoTDBGroupByMonthIT.java
  tsfile/src/main/java/org/apache/iotdb/tsfile/read/filter/GroupByFilter.java
  tsfile/src/main/java/org/apache/iotdb/tsfile/read/filter/GroupByMonthFilter.java
  tsfile/src/test/java/org/apache/iotdb/tsfile/read/filter/GroupByMonthFilterTest.java
Labels: 0.12.0

#2984 [Distributed] add cluster setup example doc
  docs/UserGuide/Cluster/Cluster-Setup-Example.md
  docs/UserGuide/Cluster/Cluster-Setup.md
  docs/zh/UserGuide/Cluster/Cluster-Setup-Example.md
  docs/zh/UserGuide/Cluster/Cluster-Setup.md
Labels: Module - Cluster, Module - Documents

#2980 [To Vector] Add user guide documents of vector
  docs/UserGuide/API/Programming-Native-API.md
  docs/UserGuide/Appendix/SQL-Reference.md
  docs/UserGuide/Data-Concept/Data-Model-and-Terminology.md
  docs/UserGuide/IoTDB-SQL-Language/DDL-Data-Definition-Language.md
  docs/UserGuide/IoTDB-SQL-Language/DML-Data-Manipulation-Language.md
  docs/zh/UserGuide/API/Programming-Native-API.md
  docs/zh/UserGuide/Appendix/SQL-Reference.md
  docs/zh/UserGuide/Data-Concept/Data-Model-and-Terminology.md
  docs/zh/UserGuide/IoTDB-SQL-Language/DDL-Data-Definition-Language.md
  docs/zh/UserGuide/IoTDB-SQL-Language/DML-Data-Manipulation-Language.md
  session/src/main/java/org/apache/iotdb/session/Session.java
Labels: Module - Documents

#2986 [Distributed][To rel/0.12] add cluster setup example doc
  docs/UserGuide/Cluster/Cluster-Setup-Example.md
  docs/UserGuide/Cluster/Cluster-Setup.md
  docs/zh/UserGuide/Cluster/Cluster-Setup-Example.md
  docs/zh/UserGuide/Cluster/Cluster-Setup.md
Labels: 0.12.0, Module - Documents

#2987 optimize sync leader for meta
  cluster/src/assembly/resources/conf/iotdb-cluster.properties
  cluster/src/main/java/org/apache/iotdb/cluster/config/ClusterConfig.java
  cluster/src/main/java/org/apache/iotdb/cluster/config/ClusterDescriptor.java
  cluster/src/main/java/org/apache/iotdb/cluster/server/DataClusterServer.java
  cluster/src/main/java/org/apache/iotdb/cluster/server/MetaClusterServer.java
  cluster/src/main/java/org/apache/iotdb/cluster/server/member/RaftMember.java
  cluster/src/main/java/org/apache/iotdb/cluster/server/service/BaseAsyncService.java
  cluster/src/main/java/org/apache/iotdb/cluster/server/service/BaseSyncService.java
  cluster/src/test/java/org/apache/iotdb/cluster/query/ClusterDataQueryExecutorTest.java
  cluster/src/test/java/org/apache/iotdb/cluster/server/member/DataGroupMemberTest.java
  cluster/src/test/java/org/apache/iotdb/cluster/server/member/RaftMemberTest.java
  thrift-cluster/src/main/thrift/cluster.thrift
Labels: Module - Cluster

#2978 [IOTDB-1283] add-node.sh supports printgc
  cluster/src/assembly/resources/sbin/add-node.sh
Labels: Module - Cluster

#3002 fix release notes link
  docs/Download/README.md
Labels: Module - site

#3001 [Distributed] minor improve the concurrency problem caused by the checking apply thread and the compact entries thread
  cluster/src/main/java/org/apache/iotdb/cluster/log/catchup/LogCatchUpTask.java
  cluster/src/main/java/org/apache/iotdb/cluster/log/manage/CommittedEntryManager.java
Labels: Module - Cluster

#3008 [REL/0.12, Distributed] lowering the logging level from debug to trace when serialize meta
  cluster/src/main/java/org/apache/iotdb/cluster/log/manage/serializable/SyncLogDequeSerializer.java
Labels: 0.12.1 or 0.13, Module - Cluster

#3009 [REL/0.12, Distributed] fix the plan index miss
  server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertMultiTabletPlan.java
  server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertRowsOfOneDevicePlan.java
  server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertRowsPlan.java
Labels: Module - Cluster

#3007 [Distributed] fix the plan index miss
  server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertMultiTabletPlan.java
  server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertRowsOfOneDevicePlan.java
  server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertRowsPlan.java
Labels: Module - Cluster

#2891 [IOTDB-1254] Trigger module: windowing utility
  docs/UserGuide/Advanced-Features/Triggers.md
  docs/UserGuide/Advanced-Features/UDF-User-Defined-Function.md
  docs/UserGuide/IoTDB-SQL-Language/DML-Data-Manipulation-Language.md
  docs/zh/UserGuide/Advanced-Features/Triggers.md
  docs/zh/UserGuide/Advanced-Features/UDF-User-Defined-Function.md
  docs/zh/UserGuide/IoTDB-SQL-Language/DML-Data-Manipulation-Language.md
  server/pom.xml
  server/src/assembly/resources/conf/iotdb-engine.properties
  server/src/main/java/org/apache/iotdb/db/concurrent/ThreadName.java
  server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
  server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
  server/src/main/java/org/apache/iotdb/db/utils/windowing/api/Evaluator.java
  server/src/main/java/org/apache/iotdb/db/utils/windowing/api/Window.java
  server/src/main/java/org/apache/iotdb/db/utils/windowing/configuration/Configuration.java
  server/src/main/java/org/apache/iotdb/db/utils/windowing/configuration/SlidingSizeWindowConfiguration.java
  server/src/main/java/org/apache/iotdb/db/utils/windowing/configuration/SlidingTimeWindowConfiguration.java
  server/src/main/java/org/apache/iotdb/db/utils/windowing/exception/WindowingException.java
  server/src/main/java/org/apache/iotdb/db/utils/windowing/handler/SlidingSizeWindowEvaluationHandler.java
  server/src/main/java/org/apache/iotdb/db/utils/windowing/handler/SlidingTimeWindowEvaluationHandler.java
  server/src/main/java/org/apache/iotdb/db/utils/windowing/handler/SlidingWindowEvaluationHandler.java
  server/src/main/java/org/apache/iotdb/db/utils/windowing/runtime/WindowEvaluationTask.java
  server/src/main/java/org/apache/iotdb/db/utils/windowing/runtime/WindowEvaluationTaskPoolManager.java
  server/src/main/java/org/apache/iotdb/db/utils/windowing/window/EvictableBatchList.java
  server/src/main/java/org/apache/iotdb/db/utils/windowing/window/WindowImpl.java
  server/src/test/java/org/apache/iotdb/db/utils/windowing/SlidingSizeWindowEvaluationHandlerTest.java
  server/src/test/java/org/apache/iotdb/db/utils/windowing/SlidingTimeWindowEvaluationHandlerTest.java
  site/src/main/.vuepress/config.js
Labels: 0.12.1 or 0.13

#3032 Refactor the user documents of `API`
  docs/UserGuide/API/Programming-Cpp-Native-API.md
  docs/UserGuide/API/Programming-Go-Native-API.md
  docs/UserGuide/API/Programming-JDBC.md
  docs/UserGuide/API/Programming-Java-Native-API.md
  docs/UserGuide/API/Programming-Python-Native-API.md
  docs/UserGuide/API/Programming-TsFile-API.md
  docs/UserGuide/IoTDB-SQL-Language/DML-Data-Manipulation-Language.md
  docs/zh/UserGuide/API/Programming-Cpp-Native-API.md
  docs/zh/UserGuide/API/Programming-Go-Native-API.md
  docs/zh/UserGuide/API/Programming-JDBC.md
  docs/zh/UserGuide/API/Programming-Java-Native-API.md
  docs/zh/UserGuide/API/Programming-Python-Native-API.md
  docs/zh/UserGuide/API/Programming-TsFile-API.md
  site/src/main/.vuepress/config.js
Labels: Module - Documents

#3029 [IOTDB-1317] Log CatchUp always failed du to not check the follower's match index
  cluster/src/main/java/org/apache/iotdb/cluster/log/catchup/CatchUpTask.java
Labels: Module - Cluster, bug

#3030 [rel/0.12][IOTDB-1317] Log CatchUp always failed du to not check the follower's match index
  cluster/src/main/java/org/apache/iotdb/cluster/log/catchup/CatchUpTask.java
Labels: 0.12.1 or 0.13, Module - Cluster, bug

#3036 [To rel/0.12]minor improve the concurrency problem
  cluster/src/main/java/org/apache/iotdb/cluster/log/catchup/LogCatchUpTask.java
  cluster/src/main/java/org/apache/iotdb/cluster/log/manage/CommittedEntryManager.java
Labels: 0.12.1 or 0.13, Module - Cluster

#3039 [Distributed] update cluster-setup-example docs in config.js
  site/src/main/.vuepress/config.js
Labels: Module - Documents, Module - site

#3040 [To rel/0.12][Distributed] update cluster-setup-example docs in config.js
  site/src/main/.vuepress/config.js
Labels: Module - Documents, Module - site

#2956 [IOTDB-924] Support insert multi rows
  antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/SqlBase.g4
  docs/UserGuide/IoTDB-SQL-Language/DML-Data-Manipulation-Language.md
  docs/zh/UserGuide/IoTDB-SQL-Language/DML-Data-Manipulation-Language.md
  server/src/main/java/org/apache/iotdb/db/qp/logical/crud/InsertOperator.java
  server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java
  server/src/main/java/org/apache/iotdb/db/qp/strategy/PhysicalGenerator.java
  server/src/test/java/org/apache/iotdb/db/integration/IoTDBInsertMultiRowIT.java
Labels: 0.12.1 or 0.13, Module - Cluster

#3052 [To rel/0.12] make version change easy
  cli/pom.xml
  cluster/pom.xml
  cluster/src/main/java/org/apache/iotdb/cluster/config/ClusterConfig.java
  compile-tools/pom.xml
  example/hadoop/pom.xml
  example/udf/pom.xml
  hadoop/pom.xml
  hive-connector/pom.xml
  server/src/assembly/resources/conf/iotdb-engine.properties
  server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
  service-rpc/src/main/java/org/apache/iotdb/rpc/RpcUtils.java
  spark-tsfile/pom.xml
Labels: 0.12.1 or 0.13
