Repository apache/iotdb, pull requests merged in 2021-08, with the labels that each got.

#3698 Cherry-pick 4 bug-fixing commits about upgrade tool from rel/0.12 to master branch
  server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java
  server/src/main/java/org/apache/iotdb/db/engine/upgrade/UpgradeTask.java
  server/src/main/java/org/apache/iotdb/db/service/UpgradeSevice.java
  server/src/main/java/org/apache/iotdb/db/tools/TsFileRewriteTool.java
  server/src/main/java/org/apache/iotdb/db/tools/upgrade/TsFileOnlineUpgradeTool.java
  server/src/main/java/org/apache/iotdb/db/utils/UpgradeUtils.java
  tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/ChunkWriterImpl.java
Labels: Module - Upgrade Tool

#3692 [ISSUE-3690] Memory leaks on the server when cpp client invokes `checkTimeseriesExists`
  client-cpp/src/main/Session.cpp
Labels: Module - C++ client

#3691 [To rel/0.12][ISSUE-3690] Memory leaks on the server when cpp client invokes `checkTimeseriesExists`
  client-cpp/src/main/Session.cpp
Labels: 0.12.2

#3662 [To rel/0.12] Function Improvement: add overlapped page rate in Tracing
  server/src/main/java/org/apache/iotdb/db/query/control/QueryResourceManager.java
  server/src/main/java/org/apache/iotdb/db/query/control/TracingInfo.java
  server/src/main/java/org/apache/iotdb/db/query/control/TracingManager.java
  server/src/main/java/org/apache/iotdb/db/query/reader/series/SeriesReader.java
  server/src/main/java/org/apache/iotdb/db/query/reader/universal/DescPriorityMergeReader.java
  server/src/main/java/org/apache/iotdb/db/query/reader/universal/PriorityMergeReader.java
  server/src/test/java/org/apache/iotdb/db/query/control/TracingManagerTest.java
Labels: 0.12.2

#3670 [IOTDB-1546] [To rel/0.12] Optimize the Upgrade Tool rewrite logic to reduce the temp memory cost
  server/src/main/java/org/apache/iotdb/db/tools/TsFileRewriteTool.java
  server/src/main/java/org/apache/iotdb/db/tools/upgrade/TsFileOnlineUpgradeTool.java
Labels: Module - Upgrade Tool, 0.12.2

#3699 [To rel/0.12] MeasurementId check while create timeseries or template
  server/src/main/java/org/apache/iotdb/db/metadata/MManager.java
  server/src/main/java/org/apache/iotdb/db/metadata/MTree.java
  server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java
Labels: Module - Schema Manager, 0.12.2

#3695 [To rel/0.12] Fix CI not stop problem
  server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
  server/src/main/java/org/apache/iotdb/db/engine/StorageEngine.java
  server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionMergeTaskPoolManager.java
  server/src/main/java/org/apache/iotdb/db/engine/compaction/TsFileManagement.java
  server/src/main/java/org/apache/iotdb/db/engine/compaction/level/LevelCompactionTsFileManagement.java
  server/src/main/java/org/apache/iotdb/db/engine/merge/manage/MergeManager.java
  server/src/main/java/org/apache/iotdb/db/engine/merge/task/CompactionMergeRecoverTask.java
  server/src/main/java/org/apache/iotdb/db/engine/merge/task/MergeFileTask.java
  server/src/main/java/org/apache/iotdb/db/engine/merge/task/RecoverMergeTask.java
  server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java
  server/src/main/java/org/apache/iotdb/db/engine/version/SimpleFileVersionController.java
  server/src/test/java/org/apache/iotdb/db/integration/IoTDBAutoCreateSchemaIT.java
  server/src/test/java/org/apache/iotdb/db/integration/IoTDBCreateStorageGroupIT.java
  server/src/test/java/org/apache/iotdb/db/integration/IoTDBCreateTimeseriesIT.java
  server/src/test/java/org/apache/iotdb/db/integration/IoTDBNewTsFileCompactionIT.java
  server/src/test/java/org/apache/iotdb/db/integration/aggregation/IoTDBAggregationSmallDataIT.java
  server/src/test/java/org/apache/iotdb/db/writelog/PerformanceTest.java
Labels: 0.12.2

#3707 [To rel/0.12][IOTDB-1556] Abort auto create device while setStorageGroup exception
  server/src/main/java/org/apache/iotdb/db/exception/metadata/StorageGroupAlreadySetException.java
  server/src/main/java/org/apache/iotdb/db/metadata/MManager.java
  server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java
Labels: 0.12.2

#3705 [IOTDB-1541][To rel/0.12] Change sequence of wal and memtable in insert
  server/src/main/java/org/apache/iotdb/db/engine/memtable/AbstractMemTable.java
  server/src/main/java/org/apache/iotdb/db/engine/memtable/IMemTable.java
  server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessor.java
Labels: 0.12.2

#3660 [IOTDB-1541] Change sequence of wal and memtable in insert
  server/src/main/java/org/apache/iotdb/db/engine/memtable/AbstractMemTable.java
  server/src/main/java/org/apache/iotdb/db/engine/memtable/IMemTable.java
  server/src/main/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessor.java
Labels: Module - Storage Engine

#3658 [IOTDB-1540] [To rel/0.12] Bug Fix: 500 when using IN operator
  server/src/main/java/org/apache/iotdb/db/qp/logical/crud/InOperator.java
  server/src/main/java/org/apache/iotdb/db/qp/strategy/PhysicalGenerator.java
  server/src/main/java/org/apache/iotdb/db/qp/strategy/optimizer/ConcatPathOptimizer.java
  server/src/test/java/org/apache/iotdb/db/integration/IoTDBInIT.java
Labels: 0.12.2

#3666 [To rel/0.12] fix dead lock in compaction file selection
  server/src/assembly/resources/conf/iotdb-engine.properties
  server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
  server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
  server/src/main/java/org/apache/iotdb/db/engine/compaction/TsFileManagement.java
  server/src/main/java/org/apache/iotdb/db/engine/merge/task/CompactionMergeRecoverTask.java
  server/src/test/java/org/apache/iotdb/db/integration/IoTDBNewTsFileCompactionIT.java
Labels: 0.12.2

#3715 Fix grafana user guide
  docs/UserGuide/Ecosystem Integration/Grafana.md
  docs/zh/UserGuide/Ecosystem Integration/Grafana.md
  grafana/readme.md
  grafana/readme_zh.md
Labels: Module - Documents, Module - Grafana

#3717 [To rel/0.12] add JMX monitor to all ThreadPools in the server module
  RELEASE_NOTES.md
  server/src/main/java/org/apache/iotdb/db/concurrent/IoTDBThreadPoolFactory.java
  server/src/main/java/org/apache/iotdb/db/concurrent/threadpool/IThreadPoolMBean.java
  server/src/main/java/org/apache/iotdb/db/concurrent/threadpool/WrappedScheduledExecutorService.java
  server/src/main/java/org/apache/iotdb/db/concurrent/threadpool/WrappedScheduledExecutorServiceMBean.java
  server/src/main/java/org/apache/iotdb/db/concurrent/threadpool/WrappedSingleThreadExecutorService.java
  server/src/main/java/org/apache/iotdb/db/concurrent/threadpool/WrappedSingleThreadExecutorServiceMBean.java
  server/src/main/java/org/apache/iotdb/db/concurrent/threadpool/WrappedSingleThreadScheduledExecutor.java
  server/src/main/java/org/apache/iotdb/db/concurrent/threadpool/WrappedSingleThreadScheduledExecutorMBean.java
  server/src/main/java/org/apache/iotdb/db/concurrent/threadpool/WrappedThreadPoolExecutor.java
  server/src/main/java/org/apache/iotdb/db/concurrent/threadpool/WrappedThreadPoolExecutorMBean.java
  server/src/main/java/org/apache/iotdb/db/conf/IoTDBConstant.java
  server/src/main/java/org/apache/iotdb/db/engine/StorageEngine.java
  server/src/main/java/org/apache/iotdb/db/engine/compaction/CompactionMergeTaskPoolManager.java
  server/src/main/java/org/apache/iotdb/db/engine/flush/FlushManager.java
  server/src/main/java/org/apache/iotdb/db/engine/merge/manage/MergeManager.java
  server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java
  server/src/main/java/org/apache/iotdb/db/metadata/MManager.java
  server/src/main/java/org/apache/iotdb/db/service/MetricsService.java
  server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java
  server/src/main/java/org/apache/iotdb/db/service/UpgradeSevice.java
  server/src/main/java/org/apache/iotdb/db/writelog/manager/MultiFileLogNodeManager.java
  server/src/main/java/org/apache/iotdb/db/writelog/node/ExclusiveWriteLogNode.java
Labels: 0.12.2

#3621 [To rel/0.12] support fill by specific value
  antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/SqlBase.g4
  docs/UserGuide/IoTDB-SQL-Language/DML-Data-Manipulation-Language.md
  docs/zh/UserGuide/IoTDB-SQL-Language/DML-Data-Manipulation-Language.md
  server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java
  server/src/main/java/org/apache/iotdb/db/query/executor/fill/ValueFill.java
  server/src/test/java/org/apache/iotdb/db/integration/IoTDBFillIT.java
Labels: 0.12.2

#3747 [IOTDB-1539] [To rel/0.12] Fix delete operation with value filter is abnormal
  RELEASE_NOTES.md
  server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java
  server/src/test/java/org/apache/iotdb/db/integration/IoTDBDeletionIT.java
Labels: 0.12.2

#3748 [IOTDB-1567]fix some WAL and SG processor threadpools having the same JMX name
  pom.xml
  server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java
  server/src/main/java/org/apache/iotdb/db/writelog/node/ExclusiveWriteLogNode.java
  server/src/test/java/org/apache/iotdb/db/integration/IoTDBJMXTest.java
Labels: 0.12.2

#3749 [IOTDB-1566] [To rel/0.12] Delete the configuration:concurrent_writing_time_partition
  RELEASE_NOTES.md
  server/src/assembly/resources/conf/iotdb-engine.properties
  server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
  server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java
Labels: 0.12.2

#3770 [IOTDB-1473] Fix the bug that run SessionExample.java will be failed in
  cluster/src/main/java/org/apache/iotdb/cluster/coordinator/Coordinator.java
  cluster/src/main/java/org/apache/iotdb/cluster/server/member/DataGroupMember.java
Labels: Module - Cluster

#3689 [IOTDB-1576] Update cluster setup document
  docs/UserGuide/Cluster/Cluster-Setup-Example.md
  docs/UserGuide/Cluster/Cluster-Setup.md
  docs/zh/UserGuide/Cluster/Cluster-Setup-Example.md
  docs/zh/UserGuide/Cluster/Cluster-Setup.md
Labels: Module - Cluster, Module - Documents

#3783 claim current JDBC is not suitable for high throughput operations
  docs/UserGuide/API/Programming-JDBC.md
  docs/zh/UserGuide/API/Programming-JDBC.md
  site/src/main/.vuepress/config.js
Labels: Module - Documents

#3782 [To rel/0.12]claim current JDBC is not suitable for high throughput operations in document
  docs/UserGuide/API/Programming-JDBC.md
  docs/zh/UserGuide/API/Programming-JDBC.md
  site/src/main/.vuepress/config.js
Labels: Module - Documents

#3800 [Cherry-Pick] Cherry Pick some cluster bug-fixs from rel/0.12 to master
  cluster/src/main/java/org/apache/iotdb/cluster/coordinator/Coordinator.java
  cluster/src/main/java/org/apache/iotdb/cluster/metadata/CMManager.java
  cluster/src/main/java/org/apache/iotdb/cluster/server/MetaClusterServer.java
  server/src/main/java/org/apache/iotdb/db/metadata/MManager.java
  server/src/main/java/org/apache/iotdb/db/service/IoTDB.java
  session/src/main/java/org/apache/iotdb/session/Session.java
Labels: Module - Cluster

#3806 [To rel/0.12] [ISSUE-3805] OOM caused by Chunk cache
  RELEASE_NOTES.md
  server/src/main/java/org/apache/iotdb/db/engine/cache/ChunkCache.java
  server/src/main/java/org/apache/iotdb/db/engine/cache/TimeSeriesMetadataCache.java
Labels: 0.12.2

#3808 [IOTDB-1585][To rel/0.12] ModificationFile‘s write interface blocking
  RELEASE_NOTES.md
  server/src/main/java/org/apache/iotdb/db/engine/modification/ModificationFile.java
  server/src/main/java/org/apache/iotdb/db/engine/modification/io/ModificationWriter.java
  server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java
Labels: 0.12.2

#3812 [To rel/0.12][IOTDB-1587] SessionPool optimization: a more aggressive Session creation strategy
  RELEASE_NOTES.md
  example/session/src/main/java/org/apache/iotdb/SessionExample.java
  session/src/main/java/org/apache/iotdb/session/Session.java
  session/src/main/java/org/apache/iotdb/session/pool/SessionPool.java
  session/src/test/java/org/apache/iotdb/session/SessionUT.java
  session/src/test/java/org/apache/iotdb/session/pool/SessionPoolTest.java
Labels: 0.12.2

#3818 [To rel/0.12] [IOTDB-1580] Error result of order by time desc when enable time partition
  RELEASE_NOTES.md
  server/src/main/java/org/apache/iotdb/db/engine/compaction/level/LevelCompactionTsFileManagement.java
  server/src/test/java/org/apache/iotdb/db/integration/IoTDBTimePartitionIT.java
Labels: 0.12.2

#3810 [To rel/0.12] [IOTDB-1584] Doesn't support order by time desc in cluster mode
  RELEASE_NOTES.md
  cluster/src/main/java/org/apache/iotdb/cluster/query/reader/ClusterReaderFactory.java
  cluster/src/main/java/org/apache/iotdb/cluster/query/reader/ManagedDescPriorityMergeReader.java
  cluster/src/main/java/org/apache/iotdb/cluster/query/reader/ManagedPriorityMergeReader.java
  cluster/src/main/java/org/apache/iotdb/cluster/query/reader/mult/MultBatchReader.java
  cluster/src/test/java/org/apache/iotdb/cluster/server/member/DataGroupMemberTest.java
  server/src/main/java/org/apache/iotdb/db/utils/SerializeUtils.java
  tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/BatchData.java
  tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/DescReadBatchData.java
  tsfile/src/main/java/org/apache/iotdb/tsfile/read/common/DescReadWriteBatchData.java
Labels: 0.12.2

#3869 Fix format of Chinese CQ user doc
  docs/zh/UserGuide/Advanced-Features/Continuous-Query.md
Labels: Module - Documents

#3832 [IOTDB-1583] Raft log failed to be committed in cluster version
  cluster/src/main/java/org/apache/iotdb/cluster/server/member/RaftMember.java
  server/src/main/java/org/apache/iotdb/db/writelog/node/ExclusiveWriteLogNode.java
  server/src/test/java/org/apache/iotdb/db/writelog/WriteLogNodeTest.java
Labels: Module - Cluster

#3781 update design document of data query
  docs/SystemDesign/DataQuery/RawDataQuery.md
  docs/SystemDesign/DataQuery/SeriesReader.md
  docs/zh/SystemDesign/DataQuery/OrderByTimeQuery.md
  docs/zh/SystemDesign/DataQuery/RawDataQuery.md
  docs/zh/SystemDesign/DataQuery/SeriesReader.md
Labels: Module - Documents
