Repository apache/iotdb, pull requests merged in 2021-05, with the labels that each got.

#2976 [IOTDB-1286] fix 4 C++ mem-leak points
  client-cpp/src/main/Session.cpp
  client-cpp/src/main/Session.h
Labels: Module - C++ client

#3105 [IoTDB-1331] Add transformPath for CMManger
  cluster/src/main/java/org/apache/iotdb/cluster/metadata/CMManager.java
  server/src/main/java/org/apache/iotdb/db/metadata/MManager.java
  testcontainer/src/test/java/org/apache/iotdb/db/sql/ClusterIT.java
  testcontainer/src/test/java/org/apache/iotdb/db/sql/SingleNodeIT.java
Labels: Module - Cluster

#3118 [IOTDB-1348] Last plan not work in cluster mode
  cluster/src/main/java/org/apache/iotdb/cluster/query/last/ClusterLastQueryExecutor.java
  testcontainer/src/test/java/org/apache/iotdb/db/sql/ClusterIT.java
  testcontainer/src/test/java/org/apache/iotdb/db/sql/SingleNodeIT.java
Labels: Module - Cluster

#3142 [IOTDB-1232][IOTDB-1313] Fix lossing time precision when import csv with unsupported timestamp format
  cli/src/main/java/org/apache/iotdb/tool/AbstractCsvTool.java
  cli/src/main/java/org/apache/iotdb/tool/ExportCsv.java
  cli/src/main/java/org/apache/iotdb/tool/ImportCsv.java
Labels: 0.12.1 & 0.13

#3145 [To rel/0.12][IOTDB-1232][IOTDB-1313] Fix lossing time precision when import csv with unsupported timestamp format
  cli/src/main/java/org/apache/iotdb/tool/AbstractCsvTool.java
  cli/src/main/java/org/apache/iotdb/tool/ExportCsv.java
  cli/src/main/java/org/apache/iotdb/tool/ImportCsv.java
Labels: 0.12.1 & 0.13

#3131 [IOTDB-1316] The importCsv tool should continue inserting if a part of insertion failed
  cli/src/main/java/org/apache/iotdb/tool/ImportCsv.java
Labels: 0.12.1 & 0.13

#2080 Add continuous compaction in level compaction strategy
  server/src/assembly/resources/conf/iotdb-engine.properties
  server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
  server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
  server/src/main/java/org/apache/iotdb/db/engine/compaction/TsFileManagement.java
  server/src/main/java/org/apache/iotdb/db/engine/compaction/level/LevelCompactionTsFileManagement.java
  server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java
  server/src/test/java/org/apache/iotdb/db/engine/compaction/LevelCompactionCacheTest.java
  server/src/test/java/org/apache/iotdb/db/engine/compaction/LevelCompactionLogTest.java
  server/src/test/java/org/apache/iotdb/db/engine/compaction/LevelCompactionMergeTest.java
  server/src/test/java/org/apache/iotdb/db/engine/compaction/LevelCompactionMoreDataTest.java
  server/src/test/java/org/apache/iotdb/db/engine/compaction/NoCompactionTsFileManagementTest.java
  server/src/test/java/org/apache/iotdb/db/script/EnvScriptIT.java
Labels: Module - Compaction

#3143 [IOTDB-1352][IOTDB-1353] Rafactor E2E test, add ClusterInfo thrift based API
  cluster/src/assembly/resources/conf/iotdb-cluster.properties
  cluster/src/main/java/org/apache/iotdb/cluster/ClusterMain.java
  cluster/src/main/java/org/apache/iotdb/cluster/config/ClusterConfig.java
  cluster/src/main/java/org/apache/iotdb/cluster/config/ClusterDescriptor.java
  cluster/src/main/java/org/apache/iotdb/cluster/server/MetaClusterServer.java
  cluster/src/main/java/org/apache/iotdb/cluster/server/clusterinfo/ClusterInfoServer.java
  cluster/src/main/java/org/apache/iotdb/cluster/server/clusterinfo/ClusterInfoServerMBean.java
  cluster/src/main/java/org/apache/iotdb/cluster/server/clusterinfo/ClusterInfoServiceImpl.java
  cluster/src/main/java/org/apache/iotdb/cluster/server/clusterinfo/ClusterInfoServiceThriftHandler.java
  cluster/src/main/java/org/apache/iotdb/cluster/utils/nodetool/ClusterMonitor.java
  cluster/src/main/java/org/apache/iotdb/cluster/utils/nodetool/ClusterMonitorMBean.java
  cluster/src/test/java/org/apache/iotdb/cluster/server/clusterinfo/ClusterInfoServerTest.java
  cluster/src/test/java/org/apache/iotdb/cluster/server/clusterinfo/ClusterInfoServiceImplTest.java
  cluster/src/test/java/org/apache/iotdb/cluster/server/member/MetaGroupMemberTest.java
  docs/UserGuide/API/Programming-Java-Native-API.md
  docs/UserGuide/Cluster/Cluster-Setup.md
  docs/zh/UserGuide/API/Programming-Java-Native-API.md
  docs/zh/UserGuide/Administration-Management/Administration.md
  docs/zh/UserGuide/Cluster/Cluster-Setup.md
  server/src/main/java/org/apache/iotdb/db/concurrent/ThreadName.java
  server/src/main/java/org/apache/iotdb/db/service/ServiceType.java
  testcontainer/src/test/java/org/apache/iotdb/db/sql/Cases.java
  testcontainer/src/test/java/org/apache/iotdb/db/sql/ClusterIT.java
  testcontainer/src/test/java/org/apache/iotdb/db/sql/SingleNodeIT.java
  testcontainer/src/test/java/org/apache/iotdb/db/sql/node1/OneNodeClusterIT.java
  testcontainer/src/test/java/org/apache/iotdb/db/sql/nodes3/AbstractThreeNodeClusterIT.java
  testcontainer/src/test/java/org/apache/iotdb/db/sql/nodes3/ThreeNodeCluster1IT.java
  testcontainer/src/test/java/org/apache/iotdb/db/sql/nodes3/ThreeNodeCluster2IT.java
  testcontainer/src/test/java/org/apache/iotdb/db/sql/nodes5/AbstractFiveNodeClusterIT.java
  testcontainer/src/test/java/org/apache/iotdb/db/sql/nodes5/FiveNodeCluster1IT.java
  testcontainer/src/test/java/org/apache/iotdb/db/sql/nodes5/FiveNodeCluster2IT.java
  testcontainer/src/test/java/org/apache/iotdb/db/sql/nodes5/FiveNodeCluster4IT.java
  testcontainer/src/test/resources/1node/iotdb-cluster.properties
  thrift-cluster/src/main/thrift/cluster.thrift
  thrift-sync/pom.xml
Labels: Module - Cluster

#2958 [IOTDB-1266]SHOW TIMESERIES will only display 2000 timeseries
  cluster/src/main/java/org/apache/iotdb/cluster/metadata/CMManager.java
  server/src/main/java/org/apache/iotdb/db/qp/physical/sys/ShowPlan.java
  server/src/main/java/org/apache/iotdb/db/query/dataset/ShowDataSet.java
  testcontainer/src/test/java/org/apache/iotdb/db/sql/Cases.java
Labels: 0.12.1 & 0.13, Module - Cluster

#3183 [Distributed]Fix align by device query locally bugs in cluster module && Fix concurrent query bugs in cluster module
  cluster/src/main/java/org/apache/iotdb/cluster/query/ClusterDataQueryExecutor.java
  cluster/src/main/java/org/apache/iotdb/cluster/query/reader/ClusterReaderFactory.java
  cluster/src/main/java/org/apache/iotdb/cluster/query/reader/mult/RemoteMultSeriesReader.java
  server/src/main/java/org/apache/iotdb/db/metadata/PartialPath.java
  server/src/main/java/org/apache/iotdb/db/query/reader/series/SeriesReader.java
Labels: Hot-Fix

#3173 [IOTDB-1376] BatchProcessException was not correctly handled in BaseApplier
  cluster/src/main/java/org/apache/iotdb/cluster/log/applier/BaseApplier.java
  cluster/src/test/java/org/apache/iotdb/cluster/log/applier/DataLogApplierTest.java
  server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java
  server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java
  server/src/main/java/org/apache/iotdb/db/qp/physical/BatchPlan.java
  server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertMultiTabletPlan.java
  server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertRowsOfOneDevicePlan.java
  server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertRowsPlan.java
  server/src/main/java/org/apache/iotdb/db/qp/physical/sys/CreateMultiTimeSeriesPlan.java
Labels: 0.12.1 & 0.13, Module - Cluster

#3139 [ISSUE-3116] Bug when using natural month unit in time interval in group by query
  server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java
  server/src/main/java/org/apache/iotdb/db/qp/utils/DatetimeUtils.java
  server/src/test/java/org/apache/iotdb/db/integration/IoTDBGroupByMonthIT.java
  server/src/test/java/org/apache/iotdb/db/qp/utils/DatetimeQueryDataSetUtilsTest.java
Labels: 0.12.1 & 0.13

#3141 [To rel/0.12] [ISSUE-3116] Bug when using natural month unit in time interval in group by query
  server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java
  server/src/test/java/org/apache/iotdb/db/integration/IoTDBGroupByMonthIT.java
Labels: 0.12.1 & 0.13

#3181 Implement some JDBC methods to support DataGrip
  jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBStatement.java
Labels: Module - JDBC

#3163 [IOTDB-1259] upgrade libthrift from 0.12.0/0.13.0 to 0.14.1 and updated related classes or files
  .github/workflows/client.yml
  LICENSE-binary
  client-cpp/src/main/CMakeLists.txt
  client-cpp/src/test/CMakeLists.txt
  cluster/pom.xml
  cluster/src/main/java/org/apache/iotdb/cluster/client/async/AsyncDataClient.java
  cluster/src/main/java/org/apache/iotdb/cluster/client/async/AsyncDataHeartbeatClient.java
  cluster/src/main/java/org/apache/iotdb/cluster/client/async/AsyncMetaClient.java
  cluster/src/main/java/org/apache/iotdb/cluster/client/async/AsyncMetaHeartbeatClient.java
  cluster/src/main/java/org/apache/iotdb/cluster/client/sync/SyncDataClient.java
  cluster/src/main/java/org/apache/iotdb/cluster/client/sync/SyncDataHeartbeatClient.java
  cluster/src/main/java/org/apache/iotdb/cluster/client/sync/SyncMetaClient.java
  cluster/src/main/java/org/apache/iotdb/cluster/client/sync/SyncMetaHeartbeatClient.java
  cluster/src/test/java/org/apache/iotdb/cluster/client/sync/SyncDataClientTest.java
  cluster/src/test/java/org/apache/iotdb/cluster/client/sync/SyncMetaClientTest.java
  cluster/src/test/java/org/apache/iotdb/cluster/common/TestAsyncClientFactory.java
  cluster/src/test/java/org/apache/iotdb/cluster/common/TestSyncClientFactory.java
  cluster/src/test/java/org/apache/iotdb/cluster/log/snapshot/DataSnapshotTest.java
  cluster/src/test/java/org/apache/iotdb/cluster/log/snapshot/PullSnapshotTaskTest.java
  cluster/src/test/java/org/apache/iotdb/cluster/server/clusterinfo/ClusterInfoServerTest.java
  compile-tools/thrift/pom.xml
  jdbc/src/main/feature/feature.xml
  jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBConnection.java
  pom.xml
  server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java
  server/src/main/java/org/apache/iotdb/db/sync/conf/SyncConstant.java
  server/src/main/java/org/apache/iotdb/db/sync/sender/transfer/SyncClient.java
  server/src/test/java/org/apache/iotdb/db/utils/EnvironmentUtils.java
  service-rpc/src/main/java/org/apache/iotdb/rpc/AutoScalingBufferReadTransport.java
  service-rpc/src/main/java/org/apache/iotdb/rpc/AutoScalingBufferWriteTransport.java
  service-rpc/src/main/java/org/apache/iotdb/rpc/RpcTransportFactory.java
  service-rpc/src/main/java/org/apache/iotdb/rpc/TCompressedElasticFramedTransport.java
  service-rpc/src/main/java/org/apache/iotdb/rpc/TConfigurationConst.java
  service-rpc/src/main/java/org/apache/iotdb/rpc/TElasticFramedTransport.java
  service-rpc/src/main/java/org/apache/iotdb/rpc/TNonblockingSocketWrapper.java
  service-rpc/src/main/java/org/apache/iotdb/rpc/TSocketWrapper.java
  session/src/main/java/org/apache/iotdb/session/SessionConnection.java
  session/src/test/java/org/apache/iotdb/session/pool/SessionPoolTest.java
  session/src/test/resources/logback.xml
Labels: 0.12.1 & 0.13, Module - RPC

#3211 [To rel/0.12] Fix session UT
  session/src/test/java/org/apache/iotdb/session/SessionUT.java
Labels: 0.12.1 & 0.13

#3213 [To rel/0.12][IOTDB-1348] Last plan not work in cluster mode
  cluster/src/main/java/org/apache/iotdb/cluster/query/last/ClusterLastQueryExecutor.java
Labels: 0.12.1 & 0.13

#3222 [To rel/0.12] Fix JDK version miss-spelling
  server/src/main/java/org/apache/iotdb/db/service/StartupChecks.java
Labels: Trivial

#3223 [To rel/0.11] Fix JDK version missspelling
  server/src/main/java/org/apache/iotdb/db/service/StartupChecks.java
Labels: Trivial

#3188 [To rel/0.12] [IOTDB-1357] Compaction use append chunk merge strategy when chunk is already large enough
  server/src/main/java/org/apache/iotdb/db/engine/compaction/utils/CompactionUtils.java
  server/src/test/java/org/apache/iotdb/db/engine/compaction/CompactionChunkTest.java
  server/src/test/java/org/apache/iotdb/db/engine/compaction/LevelCompactionMergeTest.java
Labels: 0.12.1 & 0.13

#3215 [To rel/0.12] Fix import csv throw ArrayOutOfIndexError when the last value in a li…
  cli/src/main/java/org/apache/iotdb/tool/ImportCsv.java
Labels: 0.12.1 & 0.13

#3224 Fix JDK version missspelling
  server/src/main/java/org/apache/iotdb/db/service/StartupChecks.java
Labels: Trivial

#3238 [Distributed] Update cluster-setup docs
  docs/UserGuide/Cluster/Cluster-Setup-Example.md
  docs/UserGuide/Cluster/Cluster-Setup.md
  docs/zh/UserGuide/Cluster/Cluster-Setup-Example.md
  docs/zh/UserGuide/Cluster/Cluster-Setup.md
Labels: Module - Cluster, Module - Documents

#3252 [To rel/0.12][Iotdb-1385] Extract the super user to the configuration
  server/src/assembly/resources/conf/iotdb-engine.properties
  server/src/main/java/org/apache/iotdb/db/auth/AuthorityChecker.java
  server/src/main/java/org/apache/iotdb/db/auth/authorizer/LocalFileAuthorizer.java
  server/src/main/java/org/apache/iotdb/db/auth/user/BasicUserManager.java
  server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
  server/src/main/java/org/apache/iotdb/db/conf/IoTDBConstant.java
  server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
  server/src/test/java/org/apache/iotdb/db/auth/authorizer/LocalFileAuthorizerTest.java
  server/src/test/java/org/apache/iotdb/db/auth/user/LocalFileUserManagerTest.java
Labels: 0.12.1 & 0.13

#3209 Modify the getAggrResult method, don't destroy polymorphism too early
  cluster/src/main/java/org/apache/iotdb/cluster/query/LocalQueryExecutor.java
  cluster/src/main/java/org/apache/iotdb/cluster/query/aggregate/ClusterAggregator.java
  testcontainer/src/test/java/org/apache/iotdb/db/sql/Cases.java
  testcontainer/src/test/java/org/apache/iotdb/db/sql/ClusterIT.java
  testcontainer/src/test/java/org/apache/iotdb/db/sql/SingleNodeIT.java
Labels: Module - Cluster

#3274 [IOTDB-3268] Add the Chinese version of TSDB-Comparison document
  docs/UserGuide/Comparison/TSDB-Comparison.md
  docs/UserGuide/Ecosystem Integration/Zeppelin-IoTDB.md
  docs/zh/UserGuide/Comparison/TSDB-Comparison.md
  docs/zh/UserGuide/Ecosystem Integration/Zeppelin-IoTDB.md
  site/src/main/.vuepress/config.js
Labels: Module - Documents
