Repository apache/iotdb, pull requests merged in 2021-02, with the labels that each got.

#2606 [IOTDB-1137] [To rel/0.11] MNode.getLeafCount error when existing sub-device
  server/src/main/java/org/apache/iotdb/db/metadata/MManager.java
  server/src/main/java/org/apache/iotdb/db/metadata/mnode/MNode.java
  server/src/test/java/org/apache/iotdb/db/metadata/MTreeTest.java
Labels: 0.11.3

#2571 bug fix - fetch size calculation error for group by month
  server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java
  server/src/test/java/org/apache/iotdb/db/integration/IOTDBGroupByIT.java
Labels: bug

#2576 [IOTDB-1091] SDT improvement store last point
  server/src/main/java/org/apache/iotdb/db/engine/flush/MemTableFlushTask.java
  server/src/test/java/org/apache/iotdb/db/integration/IoTDBSimpleQueryIT.java
  tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/ChunkWriterImpl.java
Labels: 0.12.0

#2623 [IOTDB-1147] Fix the concurrent bug in FlushManager cause NoSuchElementException e…
  server/src/main/java/org/apache/iotdb/db/engine/flush/FlushManager.java
Labels: bug

#2657 [ISSUE-2656] Update GZIP compression type in user doc
  docs/UserGuide/Concept/Compression.md
  docs/zh/UserGuide/Concept/Compression.md
Labels: Module - Documents

#2591 Add mods merge
  server/src/main/java/org/apache/iotdb/db/engine/compaction/level/LevelCompactionTsFileManagement.java
  server/src/main/java/org/apache/iotdb/db/engine/compaction/utils/CompactionUtils.java
  server/src/test/java/org/apache/iotdb/db/engine/compaction/CompactionChunkTest.java
  server/src/test/java/org/apache/iotdb/db/engine/compaction/LevelCompactionModsTest.java
  server/src/test/java/org/apache/iotdb/db/engine/compaction/LevelCompactionRecoverTest.java
Labels: 0.12.0, bug

#2670 [IOTDB-1151]fix dependency error because some jars are removed from maven's central repo
  pom.xml
Labels: 0.11.3, 0.12.0

#2582 fix sync bug for tsfiles's directory changed by vitural storage group
  cross-tests/pom.xml
  server/src/main/java/org/apache/iotdb/db/sync/sender/manage/ISyncFileManager.java
  server/src/main/java/org/apache/iotdb/db/sync/sender/manage/SyncFileManager.java
  server/src/main/java/org/apache/iotdb/db/sync/sender/transfer/ISyncClient.java
  server/src/main/java/org/apache/iotdb/db/sync/sender/transfer/SyncClient.java
  server/src/main/java/org/apache/iotdb/db/utils/SyncUtils.java
  server/src/test/java/org/apache/iotdb/db/sync/sender/manage/SyncFileManagerTest.java
  server/src/test/java/org/apache/iotdb/db/sync/sender/recover/SyncSenderLogAnalyzerTest.java
  server/src/test/java/org/apache/iotdb/db/sync/sender/transfer/SyncClientTest.java
Labels: 0.12.0, bug

#2613 fix importCSVTool import directory bug & encode bug
  cli/src/main/java/org/apache/iotdb/tool/ImportCsv.java
  jdbc/src/main/java/org/apache/iotdb/jdbc/AbstractIoTDBJDBCResultSet.java
  tsfile/src/main/java/org/apache/iotdb/tsfile/utils/PublicBAOS.java
Labels: 0.12.0, bug

#2669 doc: fix prerequisites about of maven version
  README.md
  README_ZH.md
  docs/UserGuide/Client/Programming - JDBC.md
  docs/UserGuide/Client/Programming - Native API.md
  docs/UserGuide/Server/Download.md
  docs/zh/UserGuide/Client/Programming - JDBC.md
  docs/zh/UserGuide/Client/Programming - Native API.md
  docs/zh/UserGuide/Server/Download.md
  jdbc/README.md
Labels: Module - Documents

#2599 [ISSUE-2598] Throw explicit exception when time series is unknown in where clause
  server/src/main/java/org/apache/iotdb/db/qp/strategy/optimizer/ConcatPathOptimizer.java
  server/src/test/java/org/apache/iotdb/db/integration/IoTDBMultiSeriesIT.java
Labels: 0.11.3, 0.12.0

#2671 [To rel/0.11] delete mods after merge
  server/src/main/java/org/apache/iotdb/db/engine/compaction/level/LevelCompactionTsFileManagement.java
  server/src/main/java/org/apache/iotdb/db/engine/compaction/utils/CompactionUtils.java
  server/src/test/java/org/apache/iotdb/db/engine/compaction/CompactionChunkTest.java
  server/src/test/java/org/apache/iotdb/db/engine/compaction/LevelCompactionModsTest.java
  server/src/test/java/org/apache/iotdb/db/engine/compaction/LevelCompactionRecoverTest.java
Labels: 0.11.3

#2601 Update tsdb comparison doc
  docs/UserGuide/Comparison/TSDB-Comparison.md
Labels: Module - Documents

#2699 [ISSUE-2598][To rel/0.11] Throw explicit exception when time series is unknown in where clause
  server/src/main/java/org/apache/iotdb/db/qp/strategy/optimizer/ConcatPathOptimizer.java
  server/src/test/java/org/apache/iotdb/db/integration/IoTDBMultiSeriesIT.java
Labels: 0.11.3

#2635 [IOTDB-1148]fix the client leak of client pool&use remote schema cache when check timeseries exist or not
  cluster/src/main/java/org/apache/iotdb/cluster/client/DataClientProvider.java
  cluster/src/main/java/org/apache/iotdb/cluster/metadata/CMManager.java
  cluster/src/main/java/org/apache/iotdb/cluster/metadata/MetaPuller.java
  cluster/src/main/java/org/apache/iotdb/cluster/query/ClusterPlanExecutor.java
  cluster/src/main/java/org/apache/iotdb/cluster/query/aggregate/ClusterAggregator.java
  cluster/src/main/java/org/apache/iotdb/cluster/query/groupby/RemoteGroupByExecutor.java
  cluster/src/main/java/org/apache/iotdb/cluster/query/last/ClusterLastQueryExecutor.java
  cluster/src/main/java/org/apache/iotdb/cluster/query/reader/ClusterReaderFactory.java
  cluster/src/main/java/org/apache/iotdb/cluster/query/reader/DataSourceInfo.java
  cluster/src/main/java/org/apache/iotdb/cluster/query/reader/RemoteSeriesReaderByTimestamp.java
  cluster/src/main/java/org/apache/iotdb/cluster/query/reader/RemoteSimpleSeriesReader.java
  cluster/src/main/java/org/apache/iotdb/cluster/server/ClientServer.java
  cluster/src/test/java/org/apache/iotdb/cluster/client/DataClientProviderTest.java
  tsfile/src/main/java/org/apache/iotdb/tsfile/utils/PublicBAOS.java
Labels: Module - Cluster, bug

#2672 [ISSUE-2673] Improve tests in PhysicalPlanSerializeTest
  server/src/test/java/org/apache/iotdb/db/qp/physical/PhysicalPlanSerializeTest.java
Labels: 0.12.0

#2701 fix some errors in "Config Manual.md";
  docs/zh/UserGuide/Server/Config Manual.md
Labels: Module - Documents

#2616 [ISSUE-2611] An unsequence file that covers too many sequence file causes OOM query
  server/src/main/java/org/apache/iotdb/db/query/reader/series/SeriesReader.java
  server/src/test/java/org/apache/iotdb/db/integration/IoTDBSeriesReaderIT.java
Labels: 0.11.3, 0.12.0, bug

#2677 [IOTDB-1135] count timeseries prefix path bug
  server/src/main/java/org/apache/iotdb/db/metadata/MTree.java
  server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java
Labels: 0.11.3, 0.12.0, Module - Schema Manager

#2717 [To rel/0.11] [IOTDB-1135] cherry pick Fix count timeseries bug when the paths are …
  server/src/main/java/org/apache/iotdb/db/metadata/MTree.java
  server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java
  server/src/test/java/org/apache/iotdb/db/metadata/MTreeTest.java
Labels: 0.11.3

#2711 Add the description about TsClean to docs
  docs/UserGuide/Operation Manual/UDF User Defined Function.md
  docs/zh/UserGuide/Operation Manual/UDF User Defined Function.md
Labels: Module - Documents

#2605 Add level merge to "merge" command
  server/src/main/java/org/apache/iotdb/db/engine/StorageEngine.java
  server/src/main/java/org/apache/iotdb/db/engine/compaction/TsFileManagement.java
  server/src/main/java/org/apache/iotdb/db/engine/compaction/level/LevelCompactionTsFileManagement.java
  server/src/main/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessor.java
  server/src/main/java/org/apache/iotdb/db/engine/storagegroup/virtualSg/VirtualStorageGroupManager.java
  server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java
  server/src/test/java/org/apache/iotdb/db/engine/storagegroup/StorageGroupProcessorTest.java
Labels: 0.11.3, 0.12.0, bug

#2667 [IOTDB-1152] optimize regular data size in traversing
  tsfile/src/main/java/org/apache/iotdb/tsfile/encoding/encoder/RegularDataEncoder.java
  tsfile/src/test/java/org/apache/iotdb/tsfile/encoding/decoder/regular/RegularDataEncoderIntegerTest.java
  tsfile/src/test/java/org/apache/iotdb/tsfile/encoding/decoder/regular/RegularDataEncoderLongTest.java
Labels: 0.12.0, Module - TsFile

#2718 [IOTDB-1172] Remove unexpected exception thrown when all CreateTimeseries opeartions are successful for CreateMultiTimeseries
  server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java
  server/src/main/java/org/apache/iotdb/db/qp/physical/sys/CreateMultiTimeSeriesPlan.java
Labels: Module - Cluster

#2723 Update ASF copyright year on website
  site/src/main/.vuepress/theme/components/Page.vue
Labels: Module - site

#2714 [IOTDB-1024] Support multiple aggregated measurements for group by level statement
  docs/UserGuide/Operation Manual/DML Data Manipulation Language.md
  docs/zh/UserGuide/Operation Manual/DML Data Manipulation Language.md
  server/src/main/java/org/apache/iotdb/db/qp/physical/crud/AggregationPlan.java
  server/src/main/java/org/apache/iotdb/db/qp/strategy/PhysicalGenerator.java
  server/src/main/java/org/apache/iotdb/db/qp/strategy/optimizer/ConcatPathOptimizer.java
  server/src/main/java/org/apache/iotdb/db/query/aggregation/impl/AvgAggrResult.java
  server/src/main/java/org/apache/iotdb/db/query/dataset/groupby/GroupByTimeDataSet.java
  server/src/main/java/org/apache/iotdb/db/query/executor/AggregationExecutor.java
  server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java
  server/src/main/java/org/apache/iotdb/db/utils/FilePathUtils.java
  server/src/test/java/org/apache/iotdb/db/integration/aggregation/IoTDBAggregationByLevelIT.java
Labels: 0.12.0

#2646 New distribution structure for v0.12
  .github/workflows/client.yml
  .github/workflows/main-unix.yml
  .github/workflows/main-win.yml
  .github/workflows/sonar-coveralls.yml
  README.md
  client-cpp/pom.xml
  client-cpp/src/assembly/client-cpp.xml
  cluster/src/assembly/cluster.xml
  compile-tools/thrift/pom.xml
  compile-tools/thrift/src/assembly/compiler.xml
  compile-tools/thrift/src/assembly/cpp.xml
  compile-tools/thrift/src/assembly/python.xml
  distribution/pom.xml
  distribution/src/assembly/all.xml
  distribution/src/assembly/cli.xml
  distribution/src/assembly/client-cpp.xml
  distribution/src/assembly/cluster.xml
  distribution/src/assembly/common-files.xml
  distribution/src/assembly/grafana.xml
  distribution/src/assembly/server.xml
  docker/src/main/Dockerfile
  example/client-cpp-example/pom.xml
  pom.xml
Labels: 0.12.0

#2698 [IOTDB-1163]optimize the insertRecords session interface for cluster version
  cluster/src/main/java/org/apache/iotdb/cluster/coordinator/Coordinator.java
  cluster/src/main/java/org/apache/iotdb/cluster/log/applier/AsyncDataLogApplier.java
  cluster/src/main/java/org/apache/iotdb/cluster/log/applier/DataLogApplier.java
  cluster/src/main/java/org/apache/iotdb/cluster/metadata/CMManager.java
  cluster/src/main/java/org/apache/iotdb/cluster/query/ClusterPlanRouter.java
  server/src/main/java/org/apache/iotdb/db/qp/executor/IPlanExecutor.java
  server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java
  server/src/main/java/org/apache/iotdb/db/qp/logical/Operator.java
  server/src/main/java/org/apache/iotdb/db/qp/physical/PhysicalPlan.java
  server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertRowPlan.java
  server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertRowsOfOneDevicePlan.java
  server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertRowsPlan.java
  server/src/main/java/org/apache/iotdb/db/service/TSServiceImpl.java
Labels: Improvement, Module - Cluster

#2468 [ISSUE-2484] Fix creating timeseries error by using "create" or "insert" statement
  cluster/src/main/java/org/apache/iotdb/cluster/metadata/CMManager.java
  server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
  server/src/main/java/org/apache/iotdb/db/metadata/MManager.java
  server/src/main/java/org/apache/iotdb/db/metadata/MTree.java
  server/src/main/java/org/apache/iotdb/db/metadata/MetaUtils.java
  server/src/main/java/org/apache/iotdb/db/metadata/mnode/MNode.java
  server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java
  server/src/test/java/org/apache/iotdb/db/integration/IoTDBAutoCreateSchemaIT.java
  server/src/test/java/org/apache/iotdb/db/integration/IoTDBCreateTimeseriesIT.java
  server/src/test/java/org/apache/iotdb/db/metadata/MTreeTest.java
  server/src/test/java/org/apache/iotdb/db/metadata/MetaUtilsTest.java
  server/src/test/java/org/apache/iotdb/db/metadata/mnode/MNodeTest.java
Labels: 0.11.3, 0.12.0, Module - Schema Manager

#2567 bug fix - skip illegal path when delete multi timeseries
  cluster/src/main/java/org/apache/iotdb/cluster/log/applier/BaseApplier.java
  server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java
  server/src/main/java/org/apache/iotdb/db/qp/physical/sys/DeleteTimeSeriesPlan.java
  session/src/test/java/org/apache/iotdb/session/IoTDBSessionSimpleIT.java
Labels: 0.11.3, 0.12.0, bug

#2619 [IOTDB-1144]support the show devices plan in distributed version
  cluster/src/main/java/org/apache/iotdb/cluster/client/sync/SyncClientAdaptor.java
  cluster/src/main/java/org/apache/iotdb/cluster/metadata/CMManager.java
  cluster/src/main/java/org/apache/iotdb/cluster/query/LocalQueryExecutor.java
  cluster/src/main/java/org/apache/iotdb/cluster/server/DataClusterServer.java
  cluster/src/main/java/org/apache/iotdb/cluster/server/handlers/caller/GetDevicesHandler.java
  cluster/src/main/java/org/apache/iotdb/cluster/server/service/DataAsyncService.java
  cluster/src/main/java/org/apache/iotdb/cluster/server/service/DataSyncService.java
  server/src/main/java/org/apache/iotdb/db/qp/physical/PhysicalPlan.java
  server/src/main/java/org/apache/iotdb/db/qp/physical/sys/ShowDevicesPlan.java
  server/src/main/java/org/apache/iotdb/db/qp/physical/sys/ShowTimeSeriesPlan.java
  server/src/main/java/org/apache/iotdb/db/query/dataset/ShowDevicesResult.java
  server/src/test/java/org/apache/iotdb/db/query/dataset/ShowDevicesResultTest.java
  thrift/src/main/thrift/cluster.thrift
Labels: Module - Cluster

#2724 filter slots for snapshots
  cluster/src/main/java/org/apache/iotdb/cluster/log/manage/FilePartitionedSnapshotLogManager.java
  cluster/src/main/java/org/apache/iotdb/cluster/log/manage/PartitionedSnapshotLogManager.java
Labels: Module - Cluster

#2735 Update system.properties change list
  server/file-changelists/system.properties-changelist.md
Labels: Module - Documents

#2731 [IOTDB-1173] auto-create schema improvement for createMultiTimeSeriesPlan
  cluster/src/main/java/org/apache/iotdb/cluster/metadata/CMManager.java
  server/src/main/java/org/apache/iotdb/db/qp/physical/crud/InsertMultiTabletPlan.java
Labels: Module - Cluster

#2689 [ISSUE-2688] LRULinkedHashMap does not work as an LRU Cache
  server/src/main/java/org/apache/iotdb/db/engine/cache/ChunkMetadataCache.java
  server/src/main/java/org/apache/iotdb/db/engine/cache/LRULinkedHashMap.java
  server/src/test/java/org/apache/iotdb/db/engine/cache/ChunkMetadataCacheTest.java
Labels: 0.11.3, 0.12.0
