Repository apache/iotdb, pull requests merged in 2022-11, with the labels that each got.

#7834 Change log level of some messages from INFO to DEBUG
  server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/LocalSinkHandle.java
  server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/LocalSourceHandle.java
  server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/MPPDataExchangeManager.java
  server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/SinkHandle.java
  server/src/main/java/org/apache/iotdb/db/mpp/execution/exchange/SourceHandle.java
  server/src/main/java/org/apache/iotdb/db/mpp/plan/Coordinator.java
  server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
  server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/QueryExecution.java
  server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/ClusterScheduler.java
  server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeInternalRPCServiceImpl.java
Labels: 1.0-alpha

#7827 [IOTDB-4738]TsFile damaged after writing empty value pages
  tsfile/src/main/java/org/apache/iotdb/tsfile/write/TsFileWriter.java
  tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/AlignedChunkGroupWriterImpl.java
  tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/AlignedChunkWriterImpl.java
  tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/ChunkWriterImpl.java
  tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/IChunkGroupWriter.java
  tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/TimeChunkWriter.java
  tsfile/src/main/java/org/apache/iotdb/tsfile/write/chunk/ValueChunkWriter.java
  tsfile/src/test/java/org/apache/iotdb/tsfile/write/TsFileWriteApiTest.java
Labels: 1.0-alpha

#7736 [IOTDB-4695] GROUP LEVEL query de-duplicates result columns unexpected
  integration-test/src/test/java/org/apache/iotdb/db/it/aggregation/IoTDBAggregationByLevelIT.java
  server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
Labels: 1.0

#7819 Modify default path of iotdb metric reporter
  confignode/src/test/resources/confignode1conf/iotdb-metric.yml
  confignode/src/test/resources/confignode2conf/iotdb-metric.yml
  confignode/src/test/resources/confignode3conf/iotdb-metric.yml
  docs/UserGuide/Maintenance-Tools/Metric-Tool.md
  docs/zh/UserGuide/Maintenance-Tools/Metric-Tool.md
  metrics/interface/src/main/assembly/resources/conf/iotdb-confignode-metric.yml
  metrics/interface/src/main/assembly/resources/conf/iotdb-datanode-metric.yml
  metrics/interface/src/main/java/org/apache/iotdb/metrics/config/MetricConfig.java
  metrics/interface/src/main/java/org/apache/iotdb/metrics/utils/IoTDBMetricsUtils.java
  metrics/interface/src/test/java/org/apache/iotdb/metrics/config/MetricConfigTest.java
  metrics/interface/src/test/resources/iotdb-metric.yml
  server/src/test/resources/datanode1conf/iotdb-metric.yml
  server/src/test/resources/datanode2conf/iotdb-metric.yml
  server/src/test/resources/datanode3conf/iotdb-metric.yml
Labels: 0.14.0-alpha

#7832 Rename StandAloneConsensus to OneCopyConsensus
  confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConfig.java
  confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeStartupCheck.java
  confignode/src/main/java/org/apache/iotdb/confignode/manager/ConsensusManager.java
  confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/RouteBalancer.java
  confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/ConfigNodeProcedureEnv.java
  confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/DataNodeRemoveHandler.java
  consensus/src/main/java/org/apache/iotdb/consensus/ConsensusFactory.java
  consensus/src/main/java/org/apache/iotdb/consensus/onecopy/OneCopyConsensus.java
  consensus/src/main/java/org/apache/iotdb/consensus/onecopy/OneCopyServerImpl.java
  consensus/src/test/java/org/apache/iotdb/consensus/multileader/MultiLeaderConsensusTest.java
  consensus/src/test/java/org/apache/iotdb/consensus/multileader/RecoveryTest.java
  consensus/src/test/java/org/apache/iotdb/consensus/onecopy/OneCopyConsensusTest.java
  consensus/src/test/java/org/apache/iotdb/consensus/onecopy/RecoveryTest.java
  consensus/src/test/java/org/apache/iotdb/consensus/ratis/RatisConsensusTest.java
  docs/UserGuide/Reference/ConfigNode-Config-Manual.md
  docs/zh/UserGuide/Reference/ConfigNode-Config-Manual.md
  integration-test/src/main/java/org/apache/iotdb/it/env/ConfigNodeWrapper.java
  integration-test/src/main/java/org/apache/iotdb/itbase/env/BaseConfig.java
  integration-test/src/test/java/org/apache/iotdb/confignode/it/IoTDBClusterNodeIT.java
  integration-test/src/test/java/org/apache/iotdb/confignode/it/IoTDBClusterPartitionIT.java
  integration-test/src/test/java/org/apache/iotdb/confignode/it/IoTDBClusterRegionLeaderBalancingIT.java
  integration-test/src/test/java/org/apache/iotdb/confignode/it/IoTDBClusterRestartIT.java
  integration-test/src/test/java/org/apache/iotdb/confignode/it/IoTDBConfigNodeSnapshotIT.java
  integration-test/src/test/java/org/apache/iotdb/confignode/it/IoTDBConfigNodeSwitchLeaderIT.java
  node-commons/src/assembly/resources/conf/iotdb-common.properties
  server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
  server/src/main/java/org/apache/iotdb/db/engine/StorageEngineV2.java
  server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
  server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaEngine.java
  server/src/main/java/org/apache/iotdb/db/metadata/schemaregion/SchemaRegionMemoryImpl.java
  server/src/main/java/org/apache/iotdb/db/mpp/execution/executor/RegionWriteExecutor.java
  server/src/main/java/org/apache/iotdb/db/service/DataNode.java
  server/src/main/java/org/apache/iotdb/db/wal/WALManager.java
  server/src/main/java/org/apache/iotdb/db/wal/recover/WALNodeRecoverTask.java
  server/src/test/java/org/apache/iotdb/db/metadata/schemaRegion/SchemaRegionSnapshotTest.java
Labels: 0.14.0-alpha

#7725 [IOTDB-4681] speed up mpp load
  node-commons/src/main/java/org/apache/iotdb/commons/partition/DataPartition.java
  server/src/main/java/org/apache/iotdb/db/engine/load/AlignedChunkData.java
  server/src/main/java/org/apache/iotdb/db/engine/load/ChunkData.java
  server/src/main/java/org/apache/iotdb/db/engine/load/DeletionData.java
  server/src/main/java/org/apache/iotdb/db/engine/load/LoadTsFileManager.java
  server/src/main/java/org/apache/iotdb/db/engine/load/NonAlignedChunkData.java
  server/src/main/java/org/apache/iotdb/db/engine/load/TsFileData.java
  server/src/main/java/org/apache/iotdb/db/engine/load/TsFileSplitter.java
  server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/AnalyzeVisitor.java
  server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/load/LoadSingleTsFileNode.java
  server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/load/LoadTsFileNode.java
  server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/plan/node/load/LoadTsFilePieceNode.java
  server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/load/LoadTsFileDispatcherImpl.java
  server/src/main/java/org/apache/iotdb/db/mpp/plan/scheduler/load/LoadTsFileScheduler.java
  server/src/main/java/org/apache/iotdb/db/utils/FileLoaderUtils.java
  server/src/main/java/org/apache/iotdb/db/utils/TimePartitionUtils.java
  tsfile/src/main/java/org/apache/iotdb/tsfile/file/header/ChunkHeader.java
  tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java
  tsfile/src/main/java/org/apache/iotdb/tsfile/write/writer/TsFileIOWriter.java
  tsfile/src/main/java/org/apache/iotdb/tsfile/write/writer/TsFileIOWriterEndFileTest.java
Labels: 1.0

#8219 [To rel/1.0] fix data inserted into incorrect data region
  node-commons/src/main/java/org/apache/iotdb/commons/partition/DataPartition.java
  server/src/test/java/org/apache/iotdb/db/mpp/plan/plan/node/write/WritePlanNodeSplitTest.java
Labels: 1.0
