Repository apache/iotdb, pull requests merged in 2022-02, with the labels that each got.

#5026 [IOTDB-2523] Fix exiting with 0 when executing error in cli
  cli/src/assembly/resources/sbin/start-cli.bat
  cli/src/assembly/resources/tools/export-csv.bat
  cli/src/assembly/resources/tools/import-csv.bat
  cli/src/main/java/org/apache/iotdb/cli/AbstractCli.java
  cli/src/main/java/org/apache/iotdb/cli/Cli.java
  cli/src/main/java/org/apache/iotdb/tool/AbstractCsvTool.java
  cli/src/main/java/org/apache/iotdb/tool/ExportCsv.java
  cli/src/main/java/org/apache/iotdb/tool/ImportCsv.java
  cli/src/test/java/org/apache/iotdb/cli/AbstractScript.java
  cli/src/test/java/org/apache/iotdb/cli/StartClientScriptIT.java
  cli/src/test/java/org/apache/iotdb/tool/integration/ExportCsvTestIT.java
  cli/src/test/java/org/apache/iotdb/tool/integration/ImportCsvTestIT.java
Labels: Module - CLI

#5071 [IOTDB-2548] support date format: yyyy.MM.dd
  antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlLexer.g4
  integration/src/test/java/org/apache/iotdb/db/integration/IoTDBDatetimeFormatIT.java
Labels: 0.13

#4985 [IOTDB-2487] Time series containing special characters can be created but connot be used normally
  antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlLexer.g4
  antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4
  docs/UserGuide/Reference/Syntax-Conventions.md
  docs/zh/UserGuide/Reference/Syntax-Conventions.md
  integration/src/test/java/org/apache/iotdb/db/integration/IoTDBDeletionIT.java
  integration/src/test/java/org/apache/iotdb/db/integration/IoTDBQuotedPathIT.java
  integration/src/test/java/org/apache/iotdb/db/integration/IoTDBSyntaxConventionIT.java
  integration/src/test/java/org/apache/iotdb/db/integration/aligned/IoTDBDeletionIT.java
  integration/src/test/java/org/apache/iotdb/db/integration/versionadaption/IoTDBSyntaxConventionVersionAdaptionIT.java
  integration/src/test/java/org/apache/iotdb/session/IoTDBSessionSimpleIT.java
  integration/src/test/java/org/apache/iotdb/session/IoTDBSessionSyntaxConventionIT.java
  server/src/main/java/org/apache/iotdb/db/metadata/utils/MetaUtils.java
  server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java
Labels: 0.13

#5057 [IOTDB-2541] Enhance /ping API to liveness probe
  docs/UserGuide/API/RestService.md
  docs/zh/UserGuide/API/RestService.md
  server/src/main/java/org/apache/iotdb/db/protocol/rest/impl/PingApiServiceImpl.java
  server/src/main/java/org/apache/iotdb/db/service/thrift/ThriftService.java
  server/src/test/java/org/apache/iotdb/db/protocol/rest/IoTDBRestServiceIT.java
Labels: Module - Restful

#5080 [IOTDB-2566]Check alignment while setting template rather than activating it
  server/src/main/java/org/apache/iotdb/db/metadata/MManager.java
  server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTree.java
  server/src/main/java/org/apache/iotdb/db/metadata/template/TemplateManager.java
  server/src/test/java/org/apache/iotdb/db/metadata/MManagerBasicTest.java
  server/src/test/java/org/apache/iotdb/db/metadata/TemplateTest.java
Labels: 0.13

#5058 [IOTDB-2546] Fix GetAllPaths() RPC call missing isUnderAligendEntity
  cluster/src/main/java/org/apache/iotdb/cluster/metadata/CMManager.java
  cluster/src/test/java/org/apache/iotdb/cluster/client/sync/SyncClientAdaptorTest.java
  thrift-cluster/src/main/thrift/cluster.thrift
Labels: Module - Cluster

#5072 [IOTDB-2557] Fix non-data-read QueryContext in getAllMeasurementSchema
  cluster/src/main/java/org/apache/iotdb/cluster/client/sync/SyncClientAdaptor.java
  cluster/src/main/java/org/apache/iotdb/cluster/metadata/CMManager.java
  cluster/src/main/java/org/apache/iotdb/cluster/query/LocalQueryExecutor.java
  cluster/src/main/java/org/apache/iotdb/cluster/server/service/DataAsyncService.java
  cluster/src/main/java/org/apache/iotdb/cluster/server/service/DataGroupServiceImpls.java
  cluster/src/main/java/org/apache/iotdb/cluster/server/service/DataSyncService.java
  cluster/src/test/java/org/apache/iotdb/cluster/client/sync/SyncClientAdaptorTest.java
  cluster/src/test/java/org/apache/iotdb/cluster/common/TestAsyncDataClient.java
  thrift-cluster/src/main/thrift/cluster.thrift
Labels: Module - Cluster

#5117 Fix invalid URL in README
  README.md
  README_ZH.md
Labels: Module - Documents

#5131 [IOTDB-2625] Fix election deadlock when updating partition table
  cluster/src/main/java/org/apache/iotdb/cluster/server/member/RaftMember.java
Labels: Module - Cluster
