Repository apache/iotdb, pull requests merged in 2022-01, with the labels that each got.

#4739 [IOTDB-2257] Add consistency checks for measurement lists size and value lists size in the SELECT statement
  antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4
  docs/UserGuide/Data-Concept/Data-Model-and-Terminology.md
  docs/UserGuide/Data-Concept/Data-Type.md
  docs/UserGuide/IoTDB-SQL-Language/DML-Data-Manipulation-Language.md
  docs/zh/UserGuide/Data-Concept/Data-Model-and-Terminology.md
  docs/zh/UserGuide/Data-Concept/Data-Type.md
  docs/zh/UserGuide/IoTDB-SQL-Language/DML-Data-Manipulation-Language.md
  integration/src/test/java/org/apache/iotdb/db/integration/IOTDBInsertIT.java
  server/src/main/java/org/apache/iotdb/db/qp/logical/crud/InsertOperator.java
  server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java
Labels: Module - SQL

#4580 [IOTDB-2111] ClusterServiceProvider: Support MQTT / REST protocols in cluster mode
  cluster/src/main/java/org/apache/iotdb/cluster/ClusterIoTDB.java
  cluster/src/main/java/org/apache/iotdb/cluster/server/ClusterTSServiceImpl.java
  cluster/src/main/java/org/apache/iotdb/cluster/server/basic/ClusterServiceProvider.java
  influxdb-protocol/src/main/java/org/apache/iotdb/influxdb/session/InfluxDBSession.java
  server/src/main/java/org/apache/iotdb/db/cq/ContinuousQueryTask.java
  server/src/main/java/org/apache/iotdb/db/protocol/influxdb/dto/IoTDBPoint.java
  server/src/main/java/org/apache/iotdb/db/protocol/influxdb/meta/InfluxDBMetaManager.java
  server/src/main/java/org/apache/iotdb/db/protocol/mqtt/PublishHandler.java
  server/src/main/java/org/apache/iotdb/db/protocol/rest/handler/AuthorizationHandler.java
  server/src/main/java/org/apache/iotdb/db/protocol/rest/impl/GrafanaApiServiceImpl.java
  server/src/main/java/org/apache/iotdb/db/protocol/rest/impl/RestApiServiceImpl.java
  server/src/main/java/org/apache/iotdb/db/query/control/SessionTimeoutManager.java
  server/src/main/java/org/apache/iotdb/db/service/IoTDB.java
  server/src/main/java/org/apache/iotdb/db/service/basic/ServiceProvider.java
  server/src/main/java/org/apache/iotdb/db/service/basic/StandaloneServiceProvider.java
  server/src/main/java/org/apache/iotdb/db/service/thrift/impl/InfluxDBServiceImpl.java
  server/src/main/java/org/apache/iotdb/db/service/thrift/impl/TSServiceImpl.java
  service-rpc/src/main/java/org/apache/iotdb/rpc/RpcUtils.java
  service-rpc/src/main/java/org/apache/iotdb/rpc/StatementExecutionException.java
Labels: Module - Cluster

#4785 [IOTDB-2325] Fix config manual which is different with system config
  docs/UserGuide/Appendix/Config-Manual.md
  docs/zh/UserGuide/Appendix/Config-Manual.md
  server/src/assembly/resources/conf/iotdb-engine.properties
Labels: Module - Documents, 0.13

#4825 [IOTDB-2392] Memory control of raft log in cluster
  cluster/src/assembly/resources/conf/iotdb-cluster.properties
  cluster/src/main/java/org/apache/iotdb/cluster/ClusterIoTDB.java
  cluster/src/main/java/org/apache/iotdb/cluster/config/ClusterConfig.java
  cluster/src/main/java/org/apache/iotdb/cluster/config/ClusterDescriptor.java
  cluster/src/main/java/org/apache/iotdb/cluster/server/Response.java
  cluster/src/main/java/org/apache/iotdb/cluster/server/handlers/caller/LogCatchUpHandler.java
  cluster/src/main/java/org/apache/iotdb/cluster/server/member/RaftMember.java
Labels: Module - Cluster

#4815 [IOTDB-2394] Fixed temporary network unavailability caused by frequent closed connections
  cluster/src/assembly/resources/conf/iotdb-cluster.properties
  cluster/src/main/java/org/apache/iotdb/cluster/client/ClientPoolFactory.java
  cluster/src/main/java/org/apache/iotdb/cluster/config/ClusterConfig.java
  cluster/src/main/java/org/apache/iotdb/cluster/config/ClusterDescriptor.java
  cluster/src/test/java/org/apache/iotdb/cluster/client/ClientPoolFactoryTest.java
Labels: Module - Cluster, Module - RPC

#4613 [IOTDB-2181] Fix cluster tag
  docs/SystemDesign/SchemaManager/SchemaManager.md
  docs/zh/SystemDesign/SchemaManager/SchemaManager.md
  integration/src/test/java/org/apache/iotdb/db/integration/IoTDBTagAlterIT.java
  integration/src/test/java/org/apache/iotdb/db/integration/IoTDBTagIT.java
  server/src/main/java/org/apache/iotdb/db/metadata/tag/TagManager.java
  testcontainer/src/test/java/org/apache/iotdb/db/sql/Cases.java
Labels: Module - Cluster, Module - Schema Manager

#4853 [IOTDB-2417]Cross compaction selector bug
  server/src/main/java/org/apache/iotdb/db/engine/compaction/cross/inplace/InplaceCompactionSelector.java
Labels: 0.13

#4862 Enable display and deletion of schema templates
  docs/UserGuide/API/Programming-Java-Native-API.md
  docs/zh/UserGuide/API/Programming-Java-Native-API.md
  server/src/main/java/org/apache/iotdb/db/metadata/MManager.java
  server/src/main/java/org/apache/iotdb/db/metadata/logfile/MLogTxtWriter.java
  server/src/main/java/org/apache/iotdb/db/metadata/logfile/MLogWriter.java
  server/src/main/java/org/apache/iotdb/db/metadata/logfile/MetadataOperationType.java
  server/src/main/java/org/apache/iotdb/db/metadata/mtree/MTree.java
  server/src/main/java/org/apache/iotdb/db/metadata/template/TemplateManager.java
  server/src/main/java/org/apache/iotdb/db/metadata/template/TemplateQueryType.java
  server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java
  server/src/main/java/org/apache/iotdb/db/qp/logical/Operator.java
  server/src/main/java/org/apache/iotdb/db/qp/physical/PhysicalPlan.java
  server/src/main/java/org/apache/iotdb/db/qp/physical/sys/DropTemplatePlan.java
  server/src/main/java/org/apache/iotdb/db/service/thrift/impl/TSServiceImpl.java
  server/src/main/java/org/apache/iotdb/db/tools/mlog/MLogParser.java
  server/src/test/java/org/apache/iotdb/db/metadata/TemplateTest.java
  session/src/main/java/org/apache/iotdb/session/Session.java
  session/src/main/java/org/apache/iotdb/session/SessionConnection.java
  session/src/main/java/org/apache/iotdb/session/pool/SessionPool.java
  session/src/main/java/org/apache/iotdb/session/template/TemplateQueryType.java
  session/src/test/java/org/apache/iotdb/session/template/TemplateUT.java
  thrift/rpc-changelist.md
  thrift/src/main/thrift/rpc.thrift
Labels: 0.13

#4854 [IOTDB-2412] Fetch Result Task is not taken account into query execution control
  server/src/main/java/org/apache/iotdb/db/service/thrift/impl/TSServiceImpl.java
Labels: 0.13

#4856 [IOTDB-2283] REST: support metadata query
  docs/zh/UserGuide/API/RestService.md
  openapi/src/main/openapi3/iotdb-rest.yaml
  pom.xml
  server/src/main/java/org/apache/iotdb/db/conf/rest/IoTDBRestServiceConfig.java
  server/src/main/java/org/apache/iotdb/db/protocol/rest/handler/PhysicalPlanValidationHandler.java
  server/src/main/java/org/apache/iotdb/db/protocol/rest/handler/QueryDataSetHandler.java
  server/src/main/java/org/apache/iotdb/db/protocol/rest/impl/GrafanaApiServiceImpl.java
  server/src/main/java/org/apache/iotdb/db/protocol/rest/impl/RestApiServiceImpl.java
  server/src/test/java/org/apache/iotdb/db/protocol/rest/IoTDBRestServiceIT.java
Labels: 0.13

#4881 [IOTDB-2434] IT fails on IoTDBContinuousQueryIT caused by double precision loss
  integration/src/test/java/org/apache/iotdb/db/integration/IoTDBContinuousQueryIT.java
Labels: 0.13

#4884 [IOTDB-2433] Fix aligned timeseries mem control bug
  server/src/main/java/org/apache/iotdb/db/engine/memtable/AlignedWritableMemChunkGroup.java
  server/src/test/java/org/apache/iotdb/db/engine/storagegroup/TsFileProcessorTest.java
Labels: 0.13

#4885 [IOTDB-2435] CI fails on testCreateAlignedTimeseries() because data generator is not stopped in a CQ's test
  integration/src/test/java/org/apache/iotdb/db/integration/IoTDBContinuousQueryIT.java
Labels: 0.13

#4879 Support aligned timeseries recovery in TsFileSequenceReader selfCheck
  example/tsfile/src/main/java/org/apache/iotdb/tsfile/TsFileSequenceRead.java
  server/src/main/java/org/apache/iotdb/db/tools/TsFileSketchTool.java
  server/src/test/java/org/apache/iotdb/db/engine/compaction/utils/CompactionCheckerUtils.java
  server/src/test/java/org/apache/iotdb/db/tools/TsFileSketchToolTest.java
  tsfile/src/main/java/org/apache/iotdb/tsfile/file/MetaMarker.java
  tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java
  tsfile/src/test/java/org/apache/iotdb/tsfile/write/TsFileIOWriterTest.java
  tsfile/src/test/java/org/apache/iotdb/tsfile/write/writer/AlignedChunkWriterImplTest.java
  tsfile/src/test/java/org/apache/iotdb/tsfile/write/writer/TimeChunkWriterTest.java
  tsfile/src/test/java/org/apache/iotdb/tsfile/write/writer/ValueChunkWriterTest.java
Labels: 0.13

#4891 Fix when opening too many file handlers, too many warning logs will be printed
  server/src/main/java/org/apache/iotdb/db/query/control/FileReaderManager.java
Labels: 0.13

#4893 [IOTDB-2437][Grafana Connector] can't get timeseries
  grafana-connector/src/main/java/org/apache/iotdb/web/grafana/dao/impl/BasicDaoImpl.java
Labels: 0.13

#4736 [IOTDB-2078] Split large TsFile tool
  docs/UserGuide/Maintenance-Tools/TsFile-Split-Tool.md
  docs/zh/UserGuide/Maintenance-Tools/TsFile-Split-Tool.md
  server/src/assembly/resources/tools/tsfileToolSet/split-tsfile-tool.bat
  server/src/assembly/resources/tools/tsfileToolSet/split-tsfile-tool.sh
  server/src/main/java/org/apache/iotdb/db/tools/TsFileSketchTool.java
  server/src/main/java/org/apache/iotdb/db/tools/TsFileSplitTool.java
  site/src/main/.vuepress/config.js
  tsfile/src/main/java/org/apache/iotdb/tsfile/write/writer/TsFileIOWriter.java
Labels: Module - TsFile, 0.13, Tool

#4894 Checkout User Guide documents for 0.13
  site/src/main/.vuepress/config.js
Labels: 0.13

#4895 [IOTDB-2078] [To rel/0.12] Split large TsFile tool
  docs/UserGuide/System-Tools/TsFile-Split-Tool.md
  docs/zh/UserGuide/System-Tools/TsFile-Split-Tool.md
  server/src/assembly/resources/tools/tsfileToolSet/split-tsfile-tool.bat
  server/src/assembly/resources/tools/tsfileToolSet/split-tsfile-tool.sh
  server/src/main/java/org/apache/iotdb/db/tools/TsFileSplitTool.java
  site/src/main/.vuepress/config.js
  tsfile/src/main/java/org/apache/iotdb/tsfile/read/TsFileSequenceReader.java
Labels: 0.12.5

#4906 [IOTDB-2442] Ignore CQ physical plan in sync receiver
  server/src/main/java/org/apache/iotdb/db/engine/cq/ContinuousQueryTask.java
  server/src/main/java/org/apache/iotdb/db/engine/selectinto/InsertTabletPlansIterator.java
  server/src/main/java/org/apache/iotdb/db/service/thrift/impl/TSServiceImpl.java
  server/src/main/java/org/apache/iotdb/db/sync/receiver/transfer/SyncServiceImpl.java
Labels: 0.13

#4889 [IOTDB-2413] Fix file handler not released bug
  antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlLexer.g4
  antlr/src/main/antlr4/org/apache/iotdb/db/qp/sql/IoTDBSqlParser.g4
  server/src/main/java/org/apache/iotdb/db/engine/storagegroup/timeindex/FileTimeIndex.java
  server/src/main/java/org/apache/iotdb/db/qp/constant/SQLConstant.java
  server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java
  server/src/main/java/org/apache/iotdb/db/qp/logical/Operator.java
  server/src/main/java/org/apache/iotdb/db/qp/logical/sys/ShowQueryResourceOperate.java
  server/src/main/java/org/apache/iotdb/db/qp/physical/sys/ShowPlan.java
  server/src/main/java/org/apache/iotdb/db/qp/physical/sys/ShowQueryResourcePlan.java
  server/src/main/java/org/apache/iotdb/db/qp/sql/IoTDBSqlVisitor.java
  server/src/main/java/org/apache/iotdb/db/query/control/FileReaderManager.java
  server/src/main/java/org/apache/iotdb/db/query/control/QueryFileManager.java
  server/src/main/java/org/apache/iotdb/db/query/control/QueryResourceManager.java
  server/src/main/java/org/apache/iotdb/db/rescon/TsFileResourceManager.java
Labels: 0.13

#4918 [IOTDB-2441] Msg has no status code when MULTIPLE_ERROR occurs
  integration/src/test/java/org/apache/iotdb/db/integration/IoTDBInsertMultiRowIT.java
  integration/src/test/java/org/apache/iotdb/db/integration/IoTDBSelectIntoIT.java
  integration/src/test/java/org/apache/iotdb/session/IoTDBSessionSimpleIT.java
  service-rpc/src/main/java/org/apache/iotdb/rpc/RpcUtils.java
Labels: 0.13

#4997 Fix doc of TsFileSplitTool
  docs/UserGuide/Maintenance-Tools/TsFile-Split-Tool.md
  docs/zh/UserGuide/Maintenance-Tools/TsFile-Split-Tool.md
  site/src/main/.vuepress/config.js
Labels: Module - Documents, 0.13

#4998 [TO rel/0.12] Fix doc of TsFileSplitTool
  docs/UserGuide/System-Tools/TsFile-Split-Tool.md
  docs/zh/UserGuide/System-Tools/TsFile-Split-Tool.md
Labels: Module - Documents, 0.12.5

#4936 [IOTDB-2439]Library-UDF documents on website
  docs/UserGuide/Process-Data/UDF-Library.md
  docs/zh/UserGuide/Process-Data/UDF-Library.md
  pom.xml
  site/src/main/.vuepress/config.js
  site/src/main/.vuepress/redirects
  site/src/main/package.json
Labels: Module - UDF
