Repository apache/iotdb, pull requests merged in 2022-12, with the labels that each got.

#8269 [IOTDB-4978] Fix deadLock caused by blocked operation in IntoOperator
  docs/UserGuide/Reference/Common-Config-Manual.md
  docs/zh/UserGuide/Reference/Common-Config-Manual.md
  integration-test/src/main/java/org/apache/iotdb/it/env/MppConfig.java
  integration-test/src/main/java/org/apache/iotdb/itbase/env/BaseConfig.java
  integration-test/src/test/java/org/apache/iotdb/db/it/env/StandaloneEnvConfig.java
  integration-test/src/test/java/org/apache/iotdb/db/it/selectinto/IoTDBSelectInto2IT.java
  integration-test/src/test/java/org/apache/iotdb/db/it/selectinto/IoTDBSelectInto3IT.java
  integration-test/src/test/java/org/apache/iotdb/db/it/selectinto/IoTDBSelectIntoIT.java
  node-commons/src/assembly/resources/conf/iotdb-common.properties
  server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
  server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
  server/src/main/java/org/apache/iotdb/db/mpp/execution/fragment/FragmentInstanceContext.java
  server/src/main/java/org/apache/iotdb/db/mpp/execution/fragment/FragmentInstanceManager.java
  server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/AbstractIntoOperator.java
  server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/DeviceViewIntoOperator.java
  server/src/main/java/org/apache/iotdb/db/mpp/execution/operator/process/IntoOperator.java
  server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/LocalExecutionPlanContext.java
  server/src/main/java/org/apache/iotdb/db/mpp/plan/planner/OperatorTreeGenerator.java
Labels: after 1.0

#8305 [IOTDB-4595] Add monitoring for compaction temporal files
  server/src/main/java/org/apache/iotdb/db/engine/TsFileMetricManager.java
  server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/utils/AlignedSeriesCompactionExecutor.java
  server/src/main/java/org/apache/iotdb/db/engine/compaction/inner/utils/SingleSeriesCompactionExecutor.java
  server/src/main/java/org/apache/iotdb/db/engine/compaction/performer/impl/FastCompactionPerformer.java
  server/src/main/java/org/apache/iotdb/db/engine/compaction/performer/impl/ReadChunkCompactionPerformer.java
  server/src/main/java/org/apache/iotdb/db/engine/compaction/performer/impl/ReadPointCompactionPerformer.java
  server/src/main/java/org/apache/iotdb/db/engine/compaction/writer/AbstractCompactionWriter.java
  server/src/main/java/org/apache/iotdb/db/engine/compaction/writer/AbstractCrossCompactionWriter.java
  server/src/main/java/org/apache/iotdb/db/engine/compaction/writer/AbstractInnerCompactionWriter.java
  server/src/main/java/org/apache/iotdb/db/service/metrics/FileMetrics.java
Labels: after 1.0

#8429 [To rel/1.0][IOTDB-5185] The old snapshot is not deleted after “ take snapshot ” is complete
  consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensus.java
  consensus/src/main/java/org/apache/iotdb/consensus/iot/IoTConsensusServerImpl.java
  consensus/src/test/java/org/apache/iotdb/consensus/iot/ReplicateTest.java
  consensus/src/test/java/org/apache/iotdb/consensus/iot/StabilityTest.java
  consensus/src/test/java/org/apache/iotdb/consensus/iot/util/TestStateMachine.java
  server/src/main/java/org/apache/iotdb/db/service/IoTDBShutdownHook.java
Labels: 1.0

#8468 [To rel/1.0][IOTDB-5174] Use filename format such as NodeID-Index rather than End…
  consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/IndexController.java
  consensus/src/main/java/org/apache/iotdb/consensus/iot/logdispatcher/LogDispatcher.java
  consensus/src/test/java/org/apache/iotdb/consensus/iot/logdispatcher/IndexControllerTest.java
  consensus/src/test/java/org/apache/iotdb/consensus/iot/logdispatcher/SyncStatusTest.java
Labels: 1.1

#8524 [IOTDB-5173] Upgrade the level of flush metric from important to core
  docs/UserGuide/Monitor-Alert/Metric-Tool.md
  docs/zh/UserGuide/Monitor-Alert/Metric-Tool.md
  server/src/main/java/org/apache/iotdb/db/engine/flush/MemTableFlushTask.java
Labels: Module - Metrics

#8491 [To rel/0.13][IOTDB-3662] upgrade audit log
  server/src/assembly/resources/conf/iotdb-engine.properties
  server/src/main/java/org/apache/iotdb/db/audit/AuditLogOperation.java
  server/src/main/java/org/apache/iotdb/db/audit/AuditLogStorage.java
  server/src/main/java/org/apache/iotdb/db/audit/AuditLogger.java
  server/src/main/java/org/apache/iotdb/db/auth/authorizer/BasicAuthorizer.java
  server/src/main/java/org/apache/iotdb/db/auth/role/BasicRoleManager.java
  server/src/main/java/org/apache/iotdb/db/auth/user/BasicUserManager.java
  server/src/main/java/org/apache/iotdb/db/conf/IoTDBConfig.java
  server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
  server/src/main/java/org/apache/iotdb/db/protocol/mqtt/PublishHandler.java
  server/src/main/java/org/apache/iotdb/db/protocol/rest/impl/RestApiServiceImpl.java
  server/src/main/java/org/apache/iotdb/db/qp/executor/PlanExecutor.java
  server/src/main/java/org/apache/iotdb/db/qp/physical/PhysicalPlan.java
  server/src/main/java/org/apache/iotdb/db/query/control/SessionManager.java
  server/src/main/java/org/apache/iotdb/db/service/basic/ServiceProvider.java
  server/src/main/java/org/apache/iotdb/db/service/thrift/impl/TSServiceImpl.java
  server/src/test/java/org/apache/iotdb/db/qp/physical/InsertTabletMultiPlanTest.java
Labels: 0.13.4

#8544 [To rel/1.0][IOTDB-5232] Add schema memory metric
  docs/UserGuide/Monitor-Alert/Metric-Tool.md
  docs/zh/UserGuide/Monitor-Alert/Metric-Tool.md
  server/src/main/java/org/apache/iotdb/db/metadata/rescon/SchemaResourceManager.java
  server/src/main/java/org/apache/iotdb/db/metadata/rescon/SchemaResourceManagerMetrics.java
Labels: Module - Metrics

#8545 [IOTDB-5232] Add schema memory metric
  docs/UserGuide/Monitor-Alert/Metric-Tool.md
  docs/zh/UserGuide/Monitor-Alert/Metric-Tool.md
  server/src/main/java/org/apache/iotdb/db/metadata/rescon/SchemaResourceManager.java
  server/src/main/java/org/apache/iotdb/db/metadata/rescon/SchemaResourceManagerMetrics.java
Labels: Module - Metrics

#8541 [IOTDB-5250] Unify the address or port of metric module in DataNode
  server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
Labels: Module - Metrics

#8543 [To rel/1.0][IOTDB-5173] Upgrade the metric of flush from important to core (#8524)
  docs/UserGuide/Monitor-Alert/Metric-Tool.md
  docs/zh/UserGuide/Monitor-Alert/Metric-Tool.md
  server/src/main/java/org/apache/iotdb/db/engine/flush/MemTableFlushTask.java
Labels: Module - Metrics

#8552 [To rel/1.0][IOTDB-5250] Unify the address or port of metric module in DataNode (#8541)
  server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
Labels: Module - Metrics

#8523 [IOTDB-5231]Add the handle of exception when metric reporter failed to start
  metrics/interface/src/main/java/org/apache/iotdb/metrics/reporter/iotdb/InternalIoTDBReporter.java
  metrics/interface/src/main/java/org/apache/iotdb/metrics/reporter/iotdb/MemoryInternalIoTDBReporter.java
  metrics/interface/src/main/java/org/apache/iotdb/metrics/reporter/iotdb/SessionIoTDBReporter.java
  metrics/interface/src/main/java/org/apache/iotdb/metrics/reporter/prometheus/PrometheusReporter.java
  metrics/micrometer-metrics/src/main/java/org/apache/iotdb/metrics/micrometer/reporter/MicrometerJmxReporter.java
  node-commons/src/main/java/org/apache/iotdb/commons/service/metric/MetricService.java
  server/src/main/java/org/apache/iotdb/db/service/metrics/IoTDBInternalReporter.java
Labels: Module - Metrics

#8559 [To rel/1.0][IOTDB-5231]Add the handle of exception when metric reporter failed to start
  metrics/interface/src/main/java/org/apache/iotdb/metrics/reporter/iotdb/InternalIoTDBReporter.java
  metrics/interface/src/main/java/org/apache/iotdb/metrics/reporter/iotdb/MemoryInternalIoTDBReporter.java
  metrics/interface/src/main/java/org/apache/iotdb/metrics/reporter/iotdb/SessionIoTDBReporter.java
  metrics/interface/src/main/java/org/apache/iotdb/metrics/reporter/prometheus/PrometheusReporter.java
  metrics/micrometer-metrics/src/main/java/org/apache/iotdb/metrics/micrometer/reporter/MicrometerJmxReporter.java
  node-commons/src/main/java/org/apache/iotdb/commons/service/metric/MetricService.java
  server/src/main/java/org/apache/iotdb/db/service/metrics/IoTDBInternalReporter.java
Labels: Module - Metrics
