Repository apache/iotdb, pull requests merged in 2022-06, with the labels that each got.

#4965 rest services add clientAuth
  server/src/assembly/resources/conf/iotdb-rest.properties
  server/src/main/java/org/apache/iotdb/db/conf/rest/IoTDBRestServiceConfig.java
  server/src/main/java/org/apache/iotdb/db/conf/rest/IoTDBRestServiceDescriptor.java
  server/src/main/java/org/apache/iotdb/db/protocol/rest/RestService.java
  server/src/test/resources/iotdb-rest.properties
  session/src/test/resources/iotdb-rest.properties
Labels: Module - Restful

#6362 [IOTDB-3494] Fix Python-Client test
  client-py/tests/test_dataframe.py
  client-py/tests/test_one_device.py
  client-py/tests/test_tablet.py
  client-py/tests/test_todf.py
Labels: Module - Python Client

#6364 [IOTDB-3585] Support set/getFetchSize() in IT framework
  integration-test/src/main/java/org/apache/iotdb/itbase/runtime/ClusterTestStatement.java
Labels: Module - Integration-test

#6361 [IOTDB-3573] Fix IT test stucked by JDBC infinite network timeout
  .github/workflows/standalone-it-for-mpp.yml
  integration-test/pom.xml
  integration-test/src/main/java/org/apache/iotdb/it/env/AbstractEnv.java
  integration-test/src/main/java/org/apache/iotdb/it/env/AbstractNodeWrapper.java
  integration-test/src/main/java/org/apache/iotdb/itbase/runtime/ClusterTestStatement.java
  jdbc/src/main/java/org/apache/iotdb/jdbc/Config.java
  jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBConnection.java
  jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBConnectionParams.java
  jdbc/src/main/java/org/apache/iotdb/jdbc/Utils.java
  server/src/test/java/org/apache/iotdb/db/protocol/rest/GrafanaApiServiceTest.java
  server/src/test/java/org/apache/iotdb/db/protocol/rest/IoTDBRestServiceTest.java
  server/src/test/java/org/apache/iotdb/db/script/EnvScriptIT.java
Labels: Module - Integration-test, Module - JDBC

#6350 [IOTDB-3547] AddConfigNode support procedure
  confignode/src/main/java/org/apache/iotdb/confignode/client/SyncConfigNodeClientPool.java
  confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeStartupCheck.java
  confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
  confignode/src/main/java/org/apache/iotdb/confignode/manager/ConsensusManager.java
  confignode/src/main/java/org/apache/iotdb/confignode/manager/Manager.java
  confignode/src/main/java/org/apache/iotdb/confignode/manager/NodeManager.java
  confignode/src/main/java/org/apache/iotdb/confignode/manager/ProcedureManager.java
  confignode/src/main/java/org/apache/iotdb/confignode/procedure/env/ConfigNodeProcedureEnv.java
  confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/AddConfigNodeProcedure.java
  confignode/src/main/java/org/apache/iotdb/confignode/procedure/impl/DeleteStorageGroupProcedure.java
  confignode/src/main/java/org/apache/iotdb/confignode/procedure/state/AddConfigNodeState.java
  confignode/src/main/java/org/apache/iotdb/confignode/procedure/store/ProcedureFactory.java
  confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessor.java
  server/src/main/java/org/apache/iotdb/db/client/ConfigNodeClient.java
  thrift-confignode/src/main/thrift/confignode.thrift
Labels: Module - ConfigNode

#6382 [IOTDB-3558] Dump node stacks if IT test request timeout
  integration-test/pom.xml
  integration-test/src/main/java/org/apache/iotdb/it/env/AbstractEnv.java
  integration-test/src/main/java/org/apache/iotdb/it/env/AbstractNodeWrapper.java
  integration-test/src/main/java/org/apache/iotdb/it/env/ConfigNodeWrapper.java
  integration-test/src/main/java/org/apache/iotdb/it/env/DataNodeWrapper.java
  integration-test/src/main/java/org/apache/iotdb/it/env/IoTDBTestRunner.java
  integration-test/src/main/java/org/apache/iotdb/it/env/RemoteServerEnv.java
  integration-test/src/main/java/org/apache/iotdb/it/env/StandaloneDataNodeWrapper.java
  integration-test/src/main/java/org/apache/iotdb/it/env/StandaloneOnMppEnv.java
  integration-test/src/main/java/org/apache/iotdb/itbase/env/BaseEnv.java
  integration-test/src/main/java/org/apache/iotdb/itbase/env/BaseNodeWrapper.java
  integration-test/src/main/java/org/apache/iotdb/itbase/runtime/InconsistentDataException.java
  integration-test/src/main/java/org/apache/iotdb/itbase/runtime/ParallelRequestDelegate.java
  integration-test/src/main/java/org/apache/iotdb/itbase/runtime/RequestDelegate.java
  integration-test/src/test/java/org/apache/iotdb/db/it/env/StandaloneEnv.java
Labels: Module - Integration-test

#6325 [IOTDB-3428] Linear expanse RegionGroup(simple version)
  confignode/src/main/java/org/apache/iotdb/confignode/client/AsyncDataNodeClientPool.java
  confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/ConfigRequest.java
  confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/ConfigRequestType.java
  confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/write/AdjustMaxRegionGroupCountReq.java
  confignode/src/main/java/org/apache/iotdb/confignode/consensus/request/write/CreateRegionsReq.java
  confignode/src/main/java/org/apache/iotdb/confignode/manager/ClusterSchemaManager.java
  confignode/src/main/java/org/apache/iotdb/confignode/manager/NodeManager.java
  confignode/src/main/java/org/apache/iotdb/confignode/manager/PartitionManager.java
  confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManager.java
  confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/RegionBalancer.java
  confignode/src/main/java/org/apache/iotdb/confignode/persistence/ClusterSchemaInfo.java
  confignode/src/main/java/org/apache/iotdb/confignode/persistence/executor/ConfigRequestExecutor.java
  confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/PartitionInfo.java
  confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/RegionGroup.java
  confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/StorageGroupPartitionTable.java
  confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessor.java
  confignode/src/test/java/org/apache/iotdb/confignode/consensus/request/ConfigRequestSerDeTest.java
  confignode/src/test/java/org/apache/iotdb/confignode/persistence/PartitionInfoTest.java
  thrift-confignode/src/main/thrift/confignode.thrift
Labels: Module - ConfigNode

#6391 [IOTDB-3622] Use hardlink to decrease the copied file size in cluster test
  .github/workflows/cluster-it.yml
  .github/workflows/standalone-it-for-mpp.yml
  integration-test/pom.xml
  integration-test/src/assembly/mpp-share.xml
  integration-test/src/assembly/mpp-test.xml
  integration-test/src/main/java/org/apache/iotdb/it/env/AbstractEnv.java
  integration-test/src/main/java/org/apache/iotdb/it/env/AbstractNodeWrapper.java
  integration-test/src/main/java/org/apache/iotdb/it/env/ConfigNodeWrapper.java
  integration-test/src/main/java/org/apache/iotdb/it/env/IoTDBTestRunner.java
  integration-test/src/script/append-to-env.sh
Labels: Module - Integration-test

#6419 Make InconsistentDataException as a RuntimeException
  integration-test/src/main/java/org/apache/iotdb/itbase/exception/InconsistentDataException.java
  integration-test/src/main/java/org/apache/iotdb/itbase/exception/ParallelRequestTimeoutException.java
  integration-test/src/main/java/org/apache/iotdb/itbase/runtime/ParallelRequestDelegate.java
  integration-test/src/main/java/org/apache/iotdb/itbase/runtime/RequestDelegate.java
Labels: Module - Integration-test

#6411 [IOTDB-3641] Fix BadNodeUrlException when loadConfigNodeList
  confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeStartupCheck.java
Labels: Module - ConfigNode

#6404 [IOTDB-3638] ConfigNode deactivate NPE
  confignode/src/main/java/org/apache/iotdb/confignode/service/ConfigNode.java
Labels: Module - ConfigNode

#6412 [IOTDB-3635][IOTDB-3583] Increase the stability of the getLeader interface
  confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
  confignode/src/main/java/org/apache/iotdb/confignode/manager/ConsensusManager.java
  confignode/src/main/java/org/apache/iotdb/confignode/manager/NodeManager.java
Labels: Module - ConfigNode

#6455 Rename iotdb-env.sh to datanode-env.sh
  README.md
  README_ZH.md
  distribution/src/assembly/all.xml
  distribution/src/assembly/server.xml
  docker/src/main/Dockerfile-single
  docker/src/main/Dockerfile-single-influxdb
  docker/src/main/Dockerfile-single-tc
  docs/UserGuide/Maintenance-Tools/JMX-Tool.md
  docs/UserGuide/QuickStart/QuickStart.md
  docs/UserGuide/QuickStart/ServerFileList.md
  docs/UserGuide/Reference/Config-Manual.md
  docs/zh/UserGuide/Maintenance-Tools/JMX-Tool.md
  docs/zh/UserGuide/QuickStart/QuickStart.md
  docs/zh/UserGuide/QuickStart/ServerFileList.md
  docs/zh/UserGuide/Reference/Config-Manual.md
  integration-test/pom.xml
  integration-test/src/assembly/mpp-test.xml
  integration-test/src/main/java/org/apache/iotdb/it/env/DataNodeWrapper.java
  node-commons/src/main/java/org/apache/iotdb/commons/conf/IoTDBConstant.java
  server/src/assembly/resources/conf/datanode-env.bat
  server/src/assembly/resources/conf/datanode-env.sh
  server/src/assembly/resources/sbin/start-datanode.bat
  server/src/assembly/resources/sbin/start-datanode.sh
  server/src/assembly/resources/sbin/start-new-server.bat
  server/src/assembly/resources/sbin/start-new-server.sh
  server/src/assembly/resources/sbin/start-server.bat
  server/src/assembly/resources/sbin/start-server.sh
  server/src/assembly/resources/tools/rocksdb-transfer.bat
  server/src/assembly/resources/tools/rocksdb-transfer.sh
  server/src/assembly/resources/tools/start-WalChecker.sh
  server/src/main/java/org/apache/iotdb/db/exception/metadata/SeriesOverflowException.java
  server/src/test/java/org/apache/iotdb/db/script/EnvScriptIT.java
Labels: 0.14.0-preview1

#6428 [IOTDB-3260] Fix npe while concurrent delete storage group
  confignode/src/main/java/org/apache/iotdb/confignode/persistence/partition/PartitionInfo.java
Labels: 0.14.0-preview1

#6475 Fix joining cluster after deactivating IoTDB DataNode
  server/src/main/java/org/apache/iotdb/db/service/DataNode.java
Labels: 0.14.0-preview1

#6451 [IOTDB-3353] Refactor insert exception processing
  server/src/main/java/org/apache/iotdb/db/consensus/statemachine/visitor/DataExecutionVisitor.java
  server/src/main/java/org/apache/iotdb/db/engine/storagegroup/DataRegion.java
  server/src/main/java/org/apache/iotdb/db/exception/BatchProcessException.java
Labels: 0.14.0-preview1

#6476 [IOTDB-3548] Fix not enough dataNode error msg
  server/src/main/java/org/apache/iotdb/db/mpp/plan/analyze/ClusterPartitionFetcher.java
Labels: 0.14.0-preview1

#6478 [IOTDB-3636] Fix delete non existing sg error msg
  confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
  server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/executor/ClusterConfigTaskExecutor.java
  server/src/main/java/org/apache/iotdb/db/mpp/plan/execution/config/executor/StandaloneConfigTaskExecutor.java
Labels: 0.14.0-preview1

#6481 Add Cluster function figure and rename thrift file and class name
  client-cpp/README.md
  client-cpp/pom.xml
  client-cpp/src/main/Session.cpp
  client-cpp/src/main/Session.h
  client-py/iotdb/Session.py
  client-py/iotdb/utils/IoTDBRpcDataSet.py
  confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCService.java
  confignode/src/main/java/org/apache/iotdb/confignode/service/thrift/ConfigNodeRPCServiceProcessor.java
  confignode/src/test/java/org/apache/iotdb/confignode/cli/TemporaryClientDemo.java
  docs/UserGuide/Cluster/Cluster-Concept.md
  docs/zh/UserGuide/Cluster/Cluster-Concept.md
  example/client-cpp-example/README.md
  jdbc/src/main/java/org/apache/iotdb/jdbc/AbstractIoTDBJDBCResultSet.java
  jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBConnection.java
  jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBDatabaseMetadata.java
  jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBJDBCResultSet.java
  jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBNonAlignJDBCResultSet.java
  jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBPreparedStatement.java
  jdbc/src/main/java/org/apache/iotdb/jdbc/IoTDBStatement.java
  jdbc/src/test/java/org/apache/iotdb/jdbc/BatchTest.java
  jdbc/src/test/java/org/apache/iotdb/jdbc/IoTDBConnectionTest.java
  jdbc/src/test/java/org/apache/iotdb/jdbc/IoTDBDatabaseMetadataTest.java
  jdbc/src/test/java/org/apache/iotdb/jdbc/IoTDBJDBCResultSetTest.java
  jdbc/src/test/java/org/apache/iotdb/jdbc/IoTDBPreparedStatementTest.java
  jdbc/src/test/java/org/apache/iotdb/jdbc/IoTDBStatementTest.java
  node-commons/src/main/java/org/apache/iotdb/commons/client/async/AsyncConfigNodeIServiceClient.java
  node-commons/src/main/java/org/apache/iotdb/commons/client/async/AsyncDataNodeInternalServiceClient.java
  node-commons/src/main/java/org/apache/iotdb/commons/client/sync/SyncConfigNodeIServiceClient.java
  node-commons/src/main/java/org/apache/iotdb/commons/client/sync/SyncDataNodeInternalServiceClient.java
  node-commons/src/test/java/org/apache/iotdb/commons/client/ClientManagerTest.java
  node-commons/src/test/java/org/apache/iotdb/commons/client/mock/MockInternalRPCService.java
  server/src/main/java/org/apache/iotdb/db/client/ConfigNodeClient.java
  server/src/main/java/org/apache/iotdb/db/service/ClientRPCService.java
  server/src/main/java/org/apache/iotdb/db/service/ClientRPCServiceMBean.java
  server/src/main/java/org/apache/iotdb/db/service/DataNode.java
  server/src/main/java/org/apache/iotdb/db/service/NewIoTDB.java
  server/src/main/java/org/apache/iotdb/db/service/RPCService.java
  server/src/main/java/org/apache/iotdb/db/service/thrift/ProcessorWithMetrics.java
  server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeRPCServiceImpl.java
  server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeTSServiceImpl.java
  server/src/main/java/org/apache/iotdb/db/service/thrift/impl/TSIEventHandler.java
  server/src/test/java/org/apache/iotdb/db/mpp/execution/schedule/DefaultDriverSchedulerTest.java
  server/src/test/java/org/apache/iotdb/db/service/ClientRPCServiceImplTest.java
  service-rpc/src/main/java/org/apache/iotdb/rpc/IoTDBJDBCDataSet.java
  service-rpc/src/main/java/org/apache/iotdb/rpc/IoTDBRpcDataSet.java
  service-rpc/src/main/java/org/apache/iotdb/rpc/RpcUtils.java
  service-rpc/src/main/java/org/apache/iotdb/rpc/SynchronizedHandler.java
  session/src/main/java/org/apache/iotdb/session/SessionConnection.java
  session/src/main/java/org/apache/iotdb/session/SessionDataSet.java
  thrift-confignode/src/main/thrift/confignode.thrift
  thrift/src/main/thrift/client.thrift
  thrift/src/main/thrift/datanode.thrift
Labels: 0.14.0-preview1

#6496 [IOTDB-3688] Prevent initializing region consensus caused by heartbeat
  server/src/main/java/org/apache/iotdb/db/consensus/DataRegionConsensusImpl.java
  server/src/main/java/org/apache/iotdb/db/consensus/SchemaRegionConsensusImpl.java
  server/src/main/java/org/apache/iotdb/db/service/DataNode.java
  server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeRPCServiceImpl.java
  server/src/test/java/org/apache/iotdb/db/service/ClientRPCServiceImplTest.java
Labels: 0.14.0-preview1

#6495 [IOTDB-3687] Rename config_nodes to target_config_nodes
  confignode/src/assembly/resources/conf/iotdb-confignode.properties
  confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeDescriptor.java
  confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeStartupCheck.java
  confignode/src/test/resources/confignode1conf/iotdb-confignode.properties
  confignode/src/test/resources/confignode2conf/iotdb-confignode.properties
  confignode/src/test/resources/confignode3conf/iotdb-confignode.properties
  docs/UserGuide/Cluster/Cluster-Setup.md
  docs/UserGuide/Reference/ConfigNode-Config-Manual.md
  docs/UserGuide/Reference/DataNode-Config-Manual.md
  docs/zh/UserGuide/Cluster/Cluster-Setup.md
  docs/zh/UserGuide/Reference/ConfigNode-Config-Manual.md
  docs/zh/UserGuide/Reference/DataNode-Config-Manual.md
  integration-test/src/main/java/org/apache/iotdb/it/env/ConfigNodeWrapper.java
  integration-test/src/main/java/org/apache/iotdb/it/env/DataNodeWrapper.java
  server/src/assembly/resources/conf/iotdb-datanode.properties
  server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
  server/src/test/resources/datanode1conf/iotdb-datanode.properties
  server/src/test/resources/datanode2conf/iotdb-datanode.properties
  server/src/test/resources/datanode3conf/iotdb-datanode.properties
Labels: 0.14.0-preview1

#6488 [IOTDB-3685] Create parameter schema_region_per_data_node and data_region_per_processor in ConfigNode
  confignode/src/assembly/resources/conf/iotdb-confignode.properties
  confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConfig.java
  confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeDescriptor.java
  confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeStartupCheck.java
  confignode/src/main/java/org/apache/iotdb/confignode/manager/ClusterSchemaManager.java
  confignode/src/main/java/org/apache/iotdb/confignode/manager/ConfigManager.java
  thrift-confignode/src/main/thrift/confignode.thrift
Labels: 0.14.0-preview1

#6494 [IOTDB-3684] Fail to read wal from wal file caused by FileNotFoundException
  server/src/main/java/org/apache/iotdb/db/wal/buffer/AbstractWALBuffer.java
  server/src/main/java/org/apache/iotdb/db/wal/buffer/WALBuffer.java
  server/src/main/java/org/apache/iotdb/db/wal/io/WALWriter.java
  server/src/main/java/org/apache/iotdb/db/wal/node/WALNode.java
  server/src/main/java/org/apache/iotdb/db/wal/utils/WALFileUtils.java
  server/src/test/java/org/apache/iotdb/db/wal/node/ConsensusReqReaderTest.java
  server/src/test/java/org/apache/iotdb/db/wal/node/WALNodeTest.java
Labels: 0.14.0-preview1

#6503 Add configuration
  server/src/main/java/org/apache/iotdb/db/conf/IoTDBDescriptor.java
Labels: 0.14.0-preview1

#6505 Add 0.14.0-preview1 release note
  RELEASE_NOTES.md
Labels: 0.14.0-preview1

#6377 [IOTDB-3509] Read/Write Routing Policy (Routing to leader)
  confignode/src/assembly/resources/conf/iotdb-confignode.properties
  confignode/src/main/java/org/apache/iotdb/confignode/client/handlers/DataNodeHeartbeatHandler.java
  confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeConfig.java
  confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeDescriptor.java
  confignode/src/main/java/org/apache/iotdb/confignode/conf/ConfigNodeStartupCheck.java
  confignode/src/main/java/org/apache/iotdb/confignode/manager/load/LoadManager.java
  confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/RouteBalancer.java
  confignode/src/main/java/org/apache/iotdb/confignode/manager/load/balancer/router/LeaderRouter.java
  confignode/src/main/java/org/apache/iotdb/confignode/manager/load/heartbeat/DataNodeHeartbeatCache.java
  confignode/src/main/java/org/apache/iotdb/confignode/manager/load/heartbeat/IRegionGroupCache.java
  confignode/src/main/java/org/apache/iotdb/confignode/manager/load/heartbeat/RegionGroupCache.java
  server/src/main/java/org/apache/iotdb/db/service/thrift/impl/DataNodeRPCServiceImpl.java
  thrift/src/main/thrift/datanode.thrift
Labels: Module - ConfigNode
